# **Preprocessing Datasets**

### **STEP 1.1 — Convert old .doc files to modern .docx files**

Why: python-docx cannot read old binary .doc files.
     LibreOffice does the conversion reliably and preserves structure.
 
Input:

    data/raw/doc/             || Original .doc files

Output:

    data/processed/docx/      || Converted .docx files

    outputs/logs/             || Conversion reports

In [5]:
import json
import hashlib
import subprocess
import time
from pathlib import Path
import re
import pandas as pd
from docx.text.paragraph import Paragraph
from collections import defaultdict
from pathlib import Path
from docx import Document
from docx.oxml.ns import qn
from docx.text.paragraph import Paragraph

In [6]:
%pip install python-docx

Requirement already satisfied: python-docx in /Users/tanggiee/anaconda3/lib/python3.11/site-packages (1.2.0)
Requirement already satisfied: lxml>=3.1.0 in /Users/tanggiee/anaconda3/lib/python3.11/site-packages (from python-docx) (5.3.0)
Requirement already satisfied: typing_extensions>=4.9.0 in /Users/tanggiee/anaconda3/lib/python3.11/site-packages (from python-docx) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import os, subprocess

os.environ["PATH"] += ":/Applications/LibreOffice.app/Contents/MacOS"  # add to PATH

# on Mac, LibreOffice binary is called "soffice" not "libreoffice"
result = subprocess.run(["which", "soffice"], capture_output=True, text=True)
print("LibreOffice found at:", result.stdout.strip() or "NOT FOUND")

# quick version check to confirm it works
version = subprocess.run(["soffice", "--version"], capture_output=True, text=True)
print("Version:", version.stdout.strip())

LibreOffice found at: /Applications/LibreOffice.app/Contents/MacOS/soffice
Version: LibreOffice 26.2.5.2 cd7284b4cbbfeb507e630c1aac019f4157393acb

In [8]:
# Folder configuration 

# Main folder of the ESG RAG project
PROJECT_ROOT = Path("/Users/tanggiee/Desktop/RAG_AI/esg_rag_project")

# Original legacy .doc documents
RAW_DOC_FOLDER = Path("/Users/tanggiee/Desktop/RAG_AI/Documents")

# Documents converted from .doc to .docx
CONVERTED_DOCX_FOLDER = PROJECT_ROOT / "data" / "processed" / "docx"

# Cleaned document text prepared for chunking
CLEANED_TEXT_FOLDER = PROJECT_ROOT / "data" / "processed" / "cleaned"

# Processing reports and error logs
LOG_FOLDER = PROJECT_ROOT / "outputs" / "logs"

# Create folders that will receive processing outputs
CONVERTED_DOCX_FOLDER.mkdir(parents=True, exist_ok=True)
CLEANED_TEXT_FOLDER.mkdir(parents=True, exist_ok=True)
LOG_FOLDER.mkdir(parents=True, exist_ok=True)

In [9]:
# create required folders 
# Create the output folders if they do not already exist
CONVERTED_DOCX_FOLDER.mkdir(parents=True, exist_ok=True)
LOG_FOLDER.mkdir(parents=True, exist_ok=True)

In [10]:
# check folders 
print(f"Original .doc files: {RAW_DOC_FOLDER.resolve()}")
print(f"Converted .docx files: {CONVERTED_DOCX_FOLDER.resolve()}")
print(f"Processing logs: {LOG_FOLDER.resolve()}")

Original .doc files: /Users/tanggiee/Desktop/RAG_AI/Documents
Converted .docx files: /Users/tanggiee/Desktop/RAG_AI/esg_rag_project/data/processed/docx
Processing logs: /Users/tanggiee/Desktop/RAG_AI/esg_rag_project/outputs/logs

**Steps**: 
- convert_single_file() converts one .doc file into .docx.
- convert_all_docs() finds and converts all .doc files in a folder, skips completed files, and saves a JSON report.

In [11]:
# Convert one legacy .doc file to .docx using LibreOffice.

def convert_single_file(doc_path: Path, output_folder: Path) -> dict:
    start_time = time.time()
    output_path = output_folder / f"{doc_path.stem}.docx"

    # Default result; values will be updated after the conversion attempt
    result = {
        "file": doc_path.name,
        "status": "failed",
        "output_path": None,
        "error": None,
        "duration_sec": None,}

    try:
        # Run LibreOffice without opening its graphical interface
        process = subprocess.run(
            [
                "soffice",
                "--headless",
                "--convert-to", "docx",
                "--outdir", str(output_folder),
                str(doc_path),
            ],
            capture_output=True,  # Capture messages from LibreOffice
            text=True,            # Return messages as normal strings
            timeout=120,          # Stop if conversion takes over 2 minutes
        )

        # A successful conversion should create the expected .docx file
        if process.returncode == 0 and output_path.exists():
            result["status"] = "success"
            result["output_path"] = str(output_path)
        else:
            result["error"] = (
                process.stderr.strip()
                or process.stdout.strip()
                or "LibreOffice did not create the expected .docx file."
            )

    except subprocess.TimeoutExpired:
        result["status"] = "timeout"
        result["error"] = "Conversion exceeded the 120-second time limit."

    except FileNotFoundError:
        result["status"] = "error"
        result["error"] = "LibreOffice is not installed or cannot be found."

    except Exception as error:
        result["status"] = "error"
        result["error"] = str(error)

    # Record the total processing time
    result["duration_sec"] = round(time.time() - start_time, 2)

    return result

In [12]:
# Convert every .doc file in a folder and save a JSON report.
def convert_all_docs(raw_folder: Path, output_folder: Path, log_folder: Path,) -> dict:

    # Make sure the required folders exist
    output_folder.mkdir(parents=True, exist_ok=True)
    log_folder.mkdir(parents=True, exist_ok=True)

    # Find all .doc files and arrange them alphabetically by filename
    doc_files = sorted(raw_folder.glob("*.doc"))

    if not doc_files:
        print(f"No .doc files found in: {raw_folder.resolve()}")
        return {}

    print(f"Found {len(doc_files)} .doc files.\n")

    results = []

    for number, doc_path in enumerate(doc_files, start=1):
        output_path = output_folder / f"{doc_path.stem}.docx"

        # Do not repeat conversions that were already completed
        if output_path.exists():
            result = {
                "file": doc_path.name,
                "status": "skipped",
                "output_path": str(output_path),
                "error": None,
                "duration_sec": 0,
            }
        else:
            result = convert_single_file(doc_path, output_folder)

        results.append(result)

        # Display progress for the current file
        print(
            f"[{number}/{len(doc_files)}] "
            f"{result['status'].upper():8} | "
            f"{result['duration_sec']:6.2f}s | "
            f"{doc_path.name}"
        )

        if result["error"]:
            print(f"    Error: {result['error']}")

    # Count each result type separately
    summary = {
        "total": len(doc_files),
        "success": sum(r["status"] == "success" for r in results),
        "skipped": sum(r["status"] == "skipped" for r in results),
        "failed": sum(
            r["status"] in {"failed", "timeout", "error"}
            for r in results
        ),
    }

    report = {
        "summary": summary,
        "files": results,}
    # Save the complete report as a readable JSON file
    report_path = log_folder / "step_01_doc_to_docx_report.json"

    with report_path.open("w", encoding="utf-8") as file:
        json.dump(report, file, indent=2, ensure_ascii=False)

    # Display the final conversion summary
    print("\n" + "=" * 50)
    print(f"Total:      {summary['total']}")
    print(f"Converted:  {summary['success']}")
    print(f"Skipped:    {summary['skipped']}")
    print(f"Failed:     {summary['failed']}")
    print(f"Report:     {report_path}")
    print("=" * 50)

    return report

In [13]:
# quick check on the number of documents 
from pathlib import Path

PROJECT_ROOT = Path("/Users/tanggiee/Desktop/RAG_AI/esg_rag_project")  # absolute path

doc_files  = list((PROJECT_ROOT / "data" / "raw" / "doc").glob("*.doc"))   # original .doc files
docx_files = list((PROJECT_ROOT / "data" / "processed" / "docx").glob("*.docx"))  # converted
txt_files  = list((PROJECT_ROOT / "data" / "processed" / "cleaned").glob("*.txt"))  # cleaned

print(f"Raw      .doc  : {len(doc_files)}")   # should be 600
print(f"Converted .docx: {len(docx_files)}")  # populated after step 1.1
print(f"Cleaned   .txt : {len(txt_files)}")   # populated after step 1.3

Raw      .doc  : 0
Converted .docx: 407
Cleaned   .txt : 406

### **STEP 1.2 — Extract Text, Metadata & ESG Classification**

Input  : data/processed/docx/

Output : data/processed/cleaned/   (one .txt per doc)

outputs/logs/corpus_registry.json

##### **a. Clean data**

In [14]:
# Find the repeated issuing bodies and remove boilerplates

# Normalize spacing so visually identical lines can be counted together
def normalize_line(line: str) -> str:
    return " ".join(line.split()).strip()


# Find repeated header/footer lines and possible issuing bodies.
def inspect_document_headers(docx_folder: Path, header_lines: int = 20, footer_lines: int = 5) -> tuple:

    docx_files = sorted(docx_folder.rglob("*.docx"))

    # Store each line or issuing body with the documents where it appears
    repeated_line_sources = defaultdict(set)
    issuing_body_sources = defaultdict(set)

    # Find authority names before words such as "promulgates"
    issuing_body_pattern = re.compile(r"(The Government|The Prime Minister|"
                                      r"Minister of [A-Za-z ,&-]+?)\s+promulgates?", 
                                      flags=re.IGNORECASE)

    for docx_path in docx_files:
        try:
            document = Document(docx_path)

            # Extract and normalize non-empty paragraphs
            lines = [normalize_line(paragraph.text)
                     for paragraph in document.paragraphs
                     if normalize_line(paragraph.text)]

            # Inspect only likely header and footer areas
            inspected_lines = lines[:header_lines] + lines[-footer_lines:]

            # Count a repeated line only once per document
            for line in set(inspected_lines):
                repeated_line_sources[line].add(docx_path.name)

            # Search the beginning of the document for the issuing authority
            header_text = "\n".join(lines[:header_lines])

            for match in issuing_body_pattern.finditer(header_text):
                issuing_body = normalize_line(match.group(1)).title()
                issuing_body_sources[issuing_body].add(docx_path.name)

        except Exception as error:
            print(f"Could not read {docx_path.name}: {error}")

    # Convert repeated-line results into a table
    repeated_lines = pd.DataFrame([
        {
            "line": line,
            "document_count": len(filenames),
            "example_files": sorted(filenames)[:5]
        }
        for line, filenames in repeated_line_sources.items()
    ])

    # Convert issuing-body results into a table
    issuing_bodies = pd.DataFrame([
        {
            "issuing_body": issuing_body,
            "document_count": len(filenames),
            "example_files": sorted(filenames)[:5]
        }
        for issuing_body, filenames in issuing_body_sources.items()
    ])

    # Show the most frequently repeated results first
    if not repeated_lines.empty:
        repeated_lines = repeated_lines.sort_values("document_count",
                                                    ascending=False).reset_index(drop=True)

    if not issuing_bodies.empty:
        issuing_bodies = issuing_bodies.sort_values("document_count",
                                                    ascending=False).reset_index(drop=True)

    return repeated_lines, issuing_bodies

In [16]:
# Load saved header inspection or run it when no checkpoint exists
REPEATED_LINES_PATH = LOG_FOLDER / "repeated_lines.json"
ISSUING_BODIES_PATH = LOG_FOLDER / "issuing_bodies.json"
FORCE_HEADER_INSPECTION = False

if REPEATED_LINES_PATH.exists() and ISSUING_BODIES_PATH.exists() and not FORCE_HEADER_INSPECTION:
    repeated_lines = pd.read_json(REPEATED_LINES_PATH)
    issuing_bodies = pd.read_json(ISSUING_BODIES_PATH)
    print(f"Loaded saved inspection: {len(repeated_lines)} repeated lines, {len(issuing_bodies)} issuing bodies.")
else:
    repeated_lines, issuing_bodies = inspect_document_headers(
        docx_folder=CONVERTED_DOCX_FOLDER, header_lines=20, footer_lines=5)
    repeated_lines.to_json(REPEATED_LINES_PATH, orient="records", indent=2, force_ascii=False)
    issuing_bodies.to_json(ISSUING_BODIES_PATH, orient="records", indent=2, force_ascii=False)
    print("Header inspection completed and saved.")

Header inspection completed and saved.

In [ ]:
# Show lines found in at least three documents
# common_lines = repeated_lines[repeated_lines["document_count"] >= 10]

# display(common_lines)
# display(issuing_bodies)

In [17]:
# Return the unique issuing bodies found by the current extraction
issuing_body_list = (issuing_bodies["issuing_body"]
                     .dropna()
                     .drop_duplicates()
                     .tolist())

# Display one issuing body per line
for issuing_body in issuing_body_list:
    print(issuing_body)

The Government
Minister Of Agriculture And Environment
Minister Of Agriculture And Rural Development
Minister Of Finance
Minister Of Industry And Trade
Minister Of Natural Resources And Environment Hereby
The Prime Minister
Minister Of Health
Minister Of Agriculture And Rural Development Hereby
Minister Of Natural Resources And Environment
Minister Of Finance Of Vietnam
Minister Of Agriculture And Environment Of Vietnam Hereby
Minister Of Construction
Minister Of Agriculture And Environment Hereby
Minister Of Health Hereby
Minister Of Industry And Trade Hereby
Minister Of Science And Technology
Minister Of Agriculture And Environment Of Vietnam
Minister Of Natural Resources And Environment Of Vietnam
Minister Of Labor - War Invalids And Social Affairs
Minister Of Natural Resources And Environment Of Vietnam Hereby
Minister Of Labour, War Invalids And Social Affairs
Minister Of Transport Hereby
Minister Of Labor, War Invalids And Social Affairs
Minister Of Agriculture And Rural Development Of Vietnam Hereby
Minister Of The Ministry Of Health
Minister Of Public Security Of Vietnam Hereby
Minister Of Information And Communications Of Vietnam
Minister Of Construction Hereby
Minister Of Vietnam
Minister Of Agriculture And Rural Development Of Vietnam
Minister Of Transport
Minister Of Finance And Jointly
Minister Of Agricultural And Rural Development
Minister Of Vietnam Hereby
Minister Of The Ministry Of Finance
Minister Of Planning And Investment
Minister Of Foreign Affairs, The Minister Of Industry And Trade And The Minister Of Public Security, The Minister Of Finance Hereby
Minister Of Labor - War Invalids And Social Affairs Hereby
Minister Of Ministry Of Agriculture And Environment
Minister Of Labor, War Invalids And Social Affairs Hereby
Minister Of Finance Of Vietnam Hereby
Minister Of Science And Technology Of Vietnam Hereby
Minister Of Finance Hereby

In [18]:
# define document types 

# Possible document-type headings found in Vietnamese legal documents
DOCUMENT_TYPE_LABELS = {
    "CONSTITUTION",
    "CODE",
    "LAW",
    "RESOLUTION",
    "JOINT RESOLUTION",
    "ORDINANCE",
    "ORDER",
    "DECREE",
    "DECISION",
    "CIRCULAR",
    "JOINT CIRCULAR",
    "DIRECTIVE",
    "NOTIFICATION"
}


def normalize_heading(text: str) -> str:
    """Remove extra spaces and standardize text for comparison."""

    return " ".join(text.upper().split()).strip(" .:-")


def identify_document_types(docx_folder: Path,
                            search_lines: int = 20) -> tuple:
    """Identify how document types are written across all .docx files."""

    # Find all converted Word documents
    docx_files = sorted(docx_folder.rglob("*.docx"))
    document_results = []

    for docx_path in docx_files:
        try:
            document = Document(docx_path)

            # Read the first non-empty paragraphs where the type normally appears
            header_lines = [paragraph.text.strip()
                            for paragraph in document.paragraphs[:search_lines]
                            if paragraph.text.strip()]

            observed_type = "UNKNOWN"
            observed_line = None

            # Find an exact document-type heading such as DECREE or CIRCULAR
            for line in header_lines:
                normalized_line = normalize_heading(line)

                if normalized_line in DOCUMENT_TYPE_LABELS:
                    observed_type = normalized_line.title()
                    observed_line = line
                    break

            # Extract the identifying portion of the filename
            filename_code = docx_path.stem.split("_m_")[0]

            document_results.append({
                "filename": docx_path.name,
                "filename_code": filename_code,
                "observed_type": observed_type,
                "observed_line": observed_line
            })

        except Exception as error:
            document_results.append({
                "filename": docx_path.name,
                "filename_code": None,
                "observed_type": "READ ERROR",
                "observed_line": str(error)
            })

    # One row for every document
    document_types = pd.DataFrame(document_results)

    # Summary of the document-type labels found
    type_summary = (document_types.groupby("observed_type", dropna=False)
                    .agg(document_count=("filename", "count"),
                         example_files=("filename",
                                        lambda files: list(files[:5])))
                    .reset_index()
                    .sort_values("document_count", ascending=False)
                    .reset_index(drop=True))

    return type_summary, document_types

In [19]:
# Identify document-type labels across the complete corpus
DOCUMENT_TYPES_PATH = LOG_FOLDER / "document_types.json"
TYPE_SUMMARY_PATH = LOG_FOLDER / "document_type_summary.json"
FORCE_TYPE_INSPECTION = False

if DOCUMENT_TYPES_PATH.exists() and TYPE_SUMMARY_PATH.exists() and not FORCE_TYPE_INSPECTION:
    document_types = pd.read_json(DOCUMENT_TYPES_PATH)
    type_summary = pd.read_json(TYPE_SUMMARY_PATH)
    print(f"Loaded saved document types: {len(document_types)} documents.")
else:
    type_summary, document_types = identify_document_types(
        docx_folder=CONVERTED_DOCX_FOLDER, search_lines=20)
    document_types.to_json(DOCUMENT_TYPES_PATH, orient="records", indent=2, force_ascii=False)
    type_summary.to_json(TYPE_SUMMARY_PATH, orient="records", indent=2, force_ascii=False)
    print("Document-type inspection completed and saved.")

Document-type inspection completed and saved.

In [20]:
# Show how document types are normally written
display(type_summary)

,observed_type,document_count,example_files
0,Circular,158,"[01_2021_TT-BXD_m_488637.docx, 01_2022_TT-BNNP..."
1,Decree,102,"[01_2019_ND-CP_m_420475.docx, 02_VBHN-BKHCN_m_..."
2,Law,64,"[02_2026_QH16_m_706740.docx, 04_2017_QH14_m_35..."
3,Decision,56,"[01_2022_QD-TTg_m_567258.docx, 04_2017_QD-TTg_..."
4,UNKNOWN,13,"[101_VBHN-VPQH_m_694902.docx, 11_VBHN-BTC_m_60..."
5,Resolution,10,"[138_NQ-CP_m_544532.docx, 189_2025_QH15_m_6536..."
6,Directive,1,[03_CT-NHNN_m_348086.docx]
7,Notification,1,[30_TB-VPCP_m_507657.docx]
8,Order,1,[11_2001_L-CTN_m_71892.docx]
9,Ordinance,1,[10_2014_UBTVQH13_m_267874.docx]

In [21]:
# Display documents whose type could not be found
unknown_document_list = document_types[document_types["observed_type"] == "UNKNOWN"]

display(unknown_document_list)

,filename,filename_code,observed_type,observed_line
67,101_VBHN-VPQH_m_694902.docx,101_VBHN-VPQH,UNKNOWN,NaN
101,11_VBHN-BTC_m_609280.docx,11_VBHN-BTC,UNKNOWN,NaN
105,125_VBHN-VPQH_m_682303.docx,125_VBHN-VPQH,UNKNOWN,NaN
154,16_2023_QH15_m_576363.docx,16_2023_QH15,UNKNOWN,NaN
171,18_VBHN-VPQH_m_699248.docx,18_VBHN-VPQH,UNKNOWN,NaN
235,308_TB-VPCP_m_494560.docx,308_TB-VPCP,UNKNOWN,NaN
260,36-NQ_TW_m_519030.docx,36-NQ_TW,UNKNOWN,NaN
285,41_2024_QH15_m_622824.docx,41_2024_QH15,UNKNOWN,NaN
298,45_2019_QH14_432162.docx,45_2019_QH14_432162,UNKNOWN,NaN
310,495_BYT-MT_m_496440.docx,495_BYT-MT,UNKNOWN,NaN
320,55-NQ_TW_m_519058.docx,55-NQ_TW,UNKNOWN,NaN
356,68_VBHN-VPQH_m_716092.docx,68_VBHN-VPQH,UNKNOWN,NaN
395,91_VBHN-VPQH_712297.docx,91_VBHN-VPQH_712297,UNKNOWN,NaN

- 101/VBHN-VPQH, 11/VBHN-BTC, 125_VBHN-VPQH, 18_VBHN-VPQH, 68_VBHN-VPQH, 91_VBHN-VPQH_712297: Integrated document
- 16/2023/QH15, 41_2024_QH15, 45/2019/QH14: Law
- 308_TB-VPCP: Announcement
- 36-NQ_TW: Resolution
- 495_BYT-MT: remove	
- 55-NQ/TW: Resolution

In [22]:
# Manually verified types for documents not identified from their headings
MANUAL_TYPE_OVERRIDES = {
    "101_VBHN-VPQH_m_694902.docx": "Integrated Document",
    "11_VBHN-BTC_m_609280.docx": "Integrated Document",
    "125_VBHN-VPQH_m_682303.docx": "Integrated Document",
    "18_VBHN-VPQH_m_699248.docx": "Integrated Document",
    "68_VBHN-VPQH_m_716092.docx": "Integrated Document",
    "91_VBHN-VPQH_712297.docx": "Integrated Document",

    "16_2023_QH15_m_576363.docx": "Law",
    "41_2024_QH15_m_622824.docx": "Law",
    "45_2019_QH14_432162.docx": "Law",

    "308_TB-VPCP_m_494560.docx": "Announcement",
    "36-NQ_TW_m_519030.docx": "Resolution",
    "55-NQ_TW_m_519058.docx": "Resolution"
}

# Files that should not be included in the regulatory corpus
EXCLUDED_FILES = {
    "495_BYT-MT_m_496440.docx"
}

In [23]:
# Replace UNKNOWN values with the manually verified document types
document_types["observed_type"] = document_types.apply(
    lambda row: MANUAL_TYPE_OVERRIDES.get(row["filename"],
                                          row["observed_type"]),
    axis=1)

# Mark excluded files without deleting the original documents
document_types["include"] = ~document_types["filename"].isin(EXCLUDED_FILES)

# Create the final document list used by the RAG pipeline
included_document_types = document_types[document_types["include"]].copy()

In [24]:
# Summarize the corrected document types
type_summary = (included_document_types.groupby("observed_type")
                .agg(document_count=("filename", "count"),
                     example_files=("filename",
                                    lambda files: list(files[:5])))
                .reset_index()
                .sort_values("document_count", ascending=False)
                .reset_index(drop=True))

display(type_summary)

,observed_type,document_count,example_files
0,Circular,158,"[01_2021_TT-BXD_m_488637.docx, 01_2022_TT-BNNP..."
1,Decree,102,"[01_2019_ND-CP_m_420475.docx, 02_VBHN-BKHCN_m_..."
2,Law,67,"[02_2026_QH16_m_706740.docx, 04_2017_QH14_m_35..."
3,Decision,56,"[01_2022_QD-TTg_m_567258.docx, 04_2017_QD-TTg_..."
4,Resolution,12,"[138_NQ-CP_m_544532.docx, 189_2025_QH15_m_6536..."
5,Integrated Document,6,"[101_VBHN-VPQH_m_694902.docx, 11_VBHN-BTC_m_60..."
6,Announcement,1,[308_TB-VPCP_m_494560.docx]
7,Directive,1,[03_CT-NHNN_m_348086.docx]
8,Notification,1,[30_TB-VPCP_m_507657.docx]
9,Order,1,[11_2001_L-CTN_m_71892.docx]
10,Ordinance,1,[10_2014_UBTVQH13_m_267874.docx]

In [25]:
# Check the final dataset after manual corrections and exclusion
print("Original documents: ", len(document_types))
print("Included documents: ", len(included_document_types))
print("Excluded documents: ", (~document_types["include"]).sum())
print("Unknown documents:  ",
      (included_document_types["observed_type"] == "UNKNOWN").sum())

Original documents:  407
Included documents:  406
Excluded documents:  1
Unknown documents:   0

In [26]:
# ── Boilerplate — non-informative lines to strip ──────────────
BOILERPLATE = {
    "SOCIALIST REPUBLIC OF VIETNAM",
    "Independence – Freedom - Happiness", "Independence - Freedom - Happiness",
    "Independence – Freedom – Happiness", "--------", "-------",
    "---------------", "----------", "OF THE POLITICAL BUREAU",
}

# Standardize boilerplate values for case-insensitive comparison
BOILERPLATE = {
    line.upper() for line in BOILERPLATE
}

In [27]:
# ── Vietnam legal document hierarchy (1=highest, 99=unknown) ──
# Based on: Vietnam's System of Legal Normative Documents chart
# Cross-referenced with actual document types observed in corpus
VIETNAM_DOC_HIERARCHY = {
    # ── National Assembly level ───────────────────────────────
    "Constitution"           : 1,
    "Code"                   : 2,   # Bộ luật
    "Law"                    : 3,   # Luật — includes Integrated/Consolidated docs (VBHN)
    "Integrated Document"    : 3,   # VBHN — merged laws, same authority level as Law
    "Resolution"             : 4,   # Nghị quyết (National Assembly / Central Committee)
    "Ordinance"              : 5,   # Pháp lệnh — observed in corpus
    "Order"                  : 6,   # Lệnh (President) — observed in corpus
    # ── Government / Prime Minister level ─────────────────────
    "Decision"               : 7,   # Quyết định — President / PM / State Auditor General
    "Decree"                 : 8,   # Nghị định → ND-CP
    "Prime Minister Decision": 9,   # Quyết định Thủ tướng → QD-TTg
    # ── Ministerial / Judicial level ──────────────────────────
    "Circular"               : 10,  # Thông tư → TT-BCT, TT-BTC etc.
    "Joint Circular"         : 10,  # Thông tư liên tịch — same level as Circular
    "Directive"              : 11,  # Chỉ thị — observed in corpus
    # ── Notifications / Announcements ─────────────────────────
    "Notification"           : 12,  # Thông báo → TB-VPCP — observed in corpus
    "Announcement"           : 12,  # Similar to Notification — not in chart, treat equally
    # ── Local level ───────────────────────────────────────────
    "Provincial Resolution"  : 13,
    "Provincial Decision"    : 14,
    "District Resolution"    : 15,
    "District Decision"      : 16,
    "Commune Resolution"     : 17,
    "Commune Decision"       : 18,
}

In [28]:
# Map filename codes to document types as a fallback when the type
# cannot be identified from the document heading
DOC_TYPE_MAP = {
    "ND-CP"      : "Decree",                "NQ-CP"     : "Resolution",
    "NQ-TW"      : "Resolution",            "QD-TTg"    : "Decision",
    "QD-UBND"    : "Decision",              "QD-CTN"    : "Decision",
    "TT-BCT"     : "Circular",              "TT-BTC"    : "Circular",
    "TT-BNNPTNT" : "Circular",              "TT-BNNMT"  : "Circular",
    "TT-BTNMT"   : "Circular",              "TT-BYT"    : "Circular",
    "TT-BKHDT"   : "Circular",              "TT-BKHCN"  : "Circular",
    "TT-BXD"     : "Circular",              "TT-BGTVT"  : "Circular",
    "TT-BLDTBXH" : "Circular",              "TT-BCA"    : "Circular",
    "TT-BQP"     : "Circular",              "TT-BTTTT"  : "Circular",
    "TT-BXD-MT"  : "Circular",              "TT-BKHCNMT": "Circular",
    "L-CTN"      : "Law",                   "QH15"      : "Law",
    "VBHN-VPQH"  : "Integrated Document",   "TB-VPCP"   : "Announcement",
    "TW"         : "Resolution",
}

In [29]:
# ── ESG taxonomy verified against ESG_law_dataset_-_ESG_Categories.pdf ──
ESG_TAXONOMY = {
    ("Environment", "Air Emissions")                                         : ["GHG Emissions", "GHG Policies", "Non-GHG Air Emissions"],
    ("Environment", "Biodiversity")                                          : ["Biodiversity", "Forests"],
    ("Environment", "Environmental management system, reporting and fines."): ["Climate Risk Management", "Environmental Fines", "Environmental Management System", "Environmental Policy", "Environmental Reporting"],
    ("Environment", "Sustainable Product Development")                       : ["Green Products", "Green Buildings", "Resource Efficiency"],
    ("Environment", "Sustainable Production")                                : ["Green Products", "Green Buildings", "Resource Efficiency", "Energy", "Hazardous Waste", "Packaging", "Toxic Spills", "Waste", "Water"],
    ("Environment", "Electromagnetic Fields")                                : ["Electromagnetic Fields"],
    ("Environment", "GMOs")                                                  : ["GMOS"],
    ("Environment", "Ozone-depleting gases")                                 : ["Ozone-Depleting Gases"],
    ("Social", "Clinical Trials")                                            : ["Clinical Trials"],
    ("Social", "Collective Bargaining and Remuneration")                     : ["Collective Bargaining", "Remuneration"],
    ("Social", "Community and Society")                                      : ["Community and Society", "Public Health", "Philanthropy"],
    ("Social", "Customer Relationship")                                      : ["Customer Relationship"],
    ("Social", "HIV Programs")                                               : ["HIV Programs"],
    ("Social", "Human Rights")                                               : ["Child Labor", "Diversity", "Human Rights", "Indigenous Rights", "Access to Basic Services", "Access to Healthcare", "Animal Welfare"],
    ("Social", "Labor Practices and Employee Development")                   : ["Employee Development", "Employee Turnover", "Health and Safety", "Labor Practices", "Unions"],
    ("Social", "Product Safety")                                             : ["Product Safety"],
    ("Social", "Responsible Marketing")                                      : ["Responsible Marketing"],
    ("Social", "Supply Chain")                                               : ["Supply Chain"],
    ("Governance", "Corporate Governance, Strategy and Sustainability")      : ["Strategy", "Board", "Board Diversity", "ESG Incentives", "Corporate Governance", "Reporting Quality", "Chairperson-CEO Separation", "Governance"],
    ("Governance", "Business Ethics")                                        : ["Business Ethics", "Anti-competitive Practices", "Corruption", "Privacy and IT"],
    ("Governance", "Financial Inclusion")                                    : ["Financial Inclusion"],
    ("Governance", "Global Compact Membership")                              : ["Global Compact Membership"],
    ("Governance", "Shareholders")                                           : ["Shareholders"],
    ("Governance", "Site Closure")                                           : ["Site Closure"],
    ("Governance", "Taxes")                                                  : ["Taxes"],
    ("Governance", "Lobbying")                                               : ["Lobbying"],
    ("Governance", "Systemic Risk")                                          : ["Systemic Risk"],
}

In [30]:
# Use one known document to test each function separately
TEST_FILE = CONVERTED_DOCX_FOLDER / "01_2019_ND-CP_m_420475.docx"

print("File exists:", TEST_FILE.exists())
print("Filename:", TEST_FILE.name)

File exists: True
Filename: 01_2019_ND-CP_m_420475.docx

In [31]:
# define
# Preserve every Domain → Group → Category path, including duplicate categories
ESG_CLASSIFICATION_PATHS = [
    (category.lower(), domain, group, category)
    for (domain, group), categories in ESG_TAXONOMY.items()
    for category in categories]

In [32]:
# test
# Check categories that occur under more than one ESG group
green_product_paths = [
    path for path in ESG_CLASSIFICATION_PATHS
    if path[0] == "green products"]

print(green_product_paths)

[('green products', 'Environment', 'Sustainable Product Development', 'Green Products'), ('green products', 'Environment', 'Sustainable Production', 'Green Products')]

In [33]:
# define 
# Extract the identifying code section from a document filename
def get_doc_code(filename: str) -> str:

    # Remove the website ID and file extension
    filename_core = Path(filename).stem.split("_m_")[0]

    # Remove a trailing website ID when "_m_" is absent
    filename_core = re.sub(r"_\d{5,}$", "", filename_core)

    return filename_core

In [34]:
# test 
# Test filename-code extraction with different formats
test_filenames = [
    "01_2019_ND-CP_m_420475.docx",
    "36-NQ_TW_m_519030.docx",
    "45_2019_QH14_432162.docx",
    "91_VBHN-VPQH_712297.docx"
]

for filename in test_filenames:
    print(filename, "→", get_doc_code(filename))

01_2019_ND-CP_m_420475.docx → 01_2019_ND-CP
36-NQ_TW_m_519030.docx → 36-NQ_TW
45_2019_QH14_432162.docx → 45_2019_QH14
91_VBHN-VPQH_712297.docx → 91_VBHN-VPQH

In [35]:
# Extract the type from document content before using filename fallback.
def get_document_type(paragraphs: list,
                      filename: str) -> tuple:

    known_types = {
        "CONSTITUTION": "Constitution",
        "CODE": "Code",
        "LAW": "Law",
        "RESOLUTION": "Resolution",
        "ORDINANCE": "Ordinance",
        "ORDER": "Order",
        "DECREE": "Decree",
        "DECISION": "Decision",
        "CIRCULAR": "Circular",
        "JOINT CIRCULAR": "Joint Circular",
        "DIRECTIVE": "Directive",
        "NOTIFICATION": "Notification",
        "ANNOUNCEMENT": "Announcement"
}

    # Search the document heading first
    for paragraph in paragraphs[:20]:
        normalized_paragraph = " ".join(paragraph.upper().split()).strip(" .:-")

        if normalized_paragraph in known_types:
            return known_types[normalized_paragraph], "document_heading"

    # Use the filename map only when no heading is found
    filename_code = get_doc_code(filename).upper().replace("_", "-")

    for code in sorted(DOC_TYPE_MAP, key=len, reverse=True):
        if code.upper() in filename_code:
            return DOC_TYPE_MAP[code], f"filename:{code}"

    return "Unknown", "not_found"

In [36]:
# Extract paragraphs and irregular tables in document order.
def get_paragraphs(docx_path: Path) -> list:
    document = Document(docx_path)
    texts = []

    for block in document.iter_inner_content():

        # Extract a normal paragraph
        if isinstance(block, Paragraph):
            text = " ".join(block.text.split())

            if text:
                texts.append(text)

        # Extract table XML without relying on the table grid
        else:
            for row_xml in block._tbl.tr_lst:
                cells = []

                for cell_xml in row_xml.tc_lst:
                    cell_text = "".join(
                        node.text or ""
                        for node in cell_xml.iter()
                        if node.tag == qn("w:t")
                    )

                    cells.append(" ".join(cell_text.split()))

                if any(cells):
                    texts.append("TABLE ROW | " + " | ".join(cells))

    return texts

In [37]:
# Test content-first document-type extraction
test_paragraphs = get_paragraphs(TEST_FILE)

document_type, type_source = get_document_type(
                                 paragraphs=test_paragraphs,
                                 filename=TEST_FILE.name)

print("Document type:", document_type)
print("Extraction source:", type_source)

Document type: Decree
Extraction source: document_heading

In [38]:
# Inspect the extracted paragraphs
test_paragraphs = get_paragraphs(TEST_FILE)

print("Paragraph count:", len(test_paragraphs))

for paragraph in test_paragraphs[:10]:
    print(paragraph)

Paragraph count: 178
TABLE ROW | THE GOVERNMENT-------- | SOCIALIST REPUBLIC OF VIETNAMIndependence – Freedom - Happiness---------------
TABLE ROW | No: 01/2019/ND-CP | Hanoi, January 01 2019
DECREE
ON FOREST RANGERS AND FOREST PROTECTION FORCES OF FOREST OWNERS
Pursuant to Law on the Government organization dated June 19 2015;
Pursuant to Law on Forestry dated November 15 2017;
At the proposal of the Minister of Natural Resources and Environment;
The Government promulgates a Decree on forest rangers and forest protection forces of forest owners.
Chapter I.
GENERAL PROVISIONS

In [39]:
# Reconstruct the official number from the filename
def get_official_number(filename: str) -> str:

    filename_core = get_doc_code(filename)

    # Convert filename separators into the official-number format
    return filename_core.replace("_", "/")

In [40]:
# Test reconstruction of official document numbers
for filename in test_filenames:
    print(filename, "→", get_official_number(filename))

01_2019_ND-CP_m_420475.docx → 01/2019/ND-CP
36-NQ_TW_m_519030.docx → 36-NQ/TW
45_2019_QH14_432162.docx → 45/2019/QH14
91_VBHN-VPQH_712297.docx → 91/VBHN-VPQH

In [41]:
# Find the first Chapter, Section or Article heading.
def find_body_start(paragraphs: list) -> int:
    body_pattern = re.compile(
        r"^(Chapter|Section|Article)\s+[A-Z0-9IVX]+[.:\s]",
        flags=re.IGNORECASE)

    for index, paragraph in enumerate(paragraphs):
        if body_pattern.match(paragraph):
            return index

    # Keep the complete document when no body heading is found
    return 0

In [42]:
# test
# Check where the substantive legal body begins
body_start = find_body_start(test_paragraphs)

print("Body starts at index:", body_start)
print("First body line:", test_paragraphs[body_start])

Body starts at index: 8
First body line: Chapter I.

In [43]:
# Extract the line following the document-type heading.
def get_title(paragraphs: list) -> str:

    document_keywords = {
        "CONSTITUTION", "CODE", "LAW", "RESOLUTION", "ORDINANCE",
        "ORDER", "DECREE", "DECISION", "CIRCULAR", "JOINT CIRCULAR",
        "DIRECTIVE", "NOTIFICATION", "ANNOUNCEMENT"
    }

    for index, paragraph in enumerate(paragraphs[:20]):
        normalized_paragraph = paragraph.upper().strip(" .:-")

        if normalized_paragraph in document_keywords:
            if index + 1 < len(paragraphs):
                return paragraphs[index + 1]

    return ""

In [44]:
# Test title extraction
document_title = get_title(test_paragraphs)

print("Title:", document_title)

Title: ON FOREST RANGERS AND FOREST PROTECTION FORCES OF FOREST OWNERS

In [45]:
# Extract the issuer from a promulgation sentence when available.

def get_issuing_body(paragraphs: list) -> str:

    issuing_pattern = re.compile(
        r"^(The Government|The Prime Minister|"
        r"Minister of [A-Za-z ,&-]+?|"
        r"Ministers? of [A-Za-z ,&-]+?)"
        r"\s+(?:hereby\s+)?(?:promulgates?|issues?|has promulgated)",
        flags=re.IGNORECASE)

    for paragraph in paragraphs[:20]:
        match = issuing_pattern.match(paragraph.strip())

        if match:
            return match.group(1).strip()

    return ""

In [46]:
# Test issuing-body extraction
issuing_body = get_issuing_body(test_paragraphs)

print("Issuing body:", issuing_body or "Not found")

Issuing body: The Government

In [47]:
# Extract a standalone issue date from the document header.
def get_issue_date(paragraphs: list) -> str:

    date_pattern = re.compile(
        r"^(?:Hanoi,\s*)?"
        r"([A-Z][a-z]+\s+\d{1,2},?\s+\d{4})$")

    for paragraph in paragraphs[:15]:
        match = date_pattern.match(paragraph.strip())

        if match:
            return match.group(1)

    return ""

In [48]:
# Blank is acceptable when the translated document omits its issue date
issue_date = get_issue_date(test_paragraphs)

print("Issue date:", issue_date or "Not found in document header")

Issue date: Not found in document header

In [49]:
# Extract an effective-date statement from the document.
def get_effective_date(paragraphs: list) -> str:

    effective_pattern = re.compile(
        r"(?:takes effect|comes into force|enters into force)"
        r"(?:\s+on|\s+from)?\s+(.+?)(?:\.|$)",
        flags=re.IGNORECASE)

    for paragraph in paragraphs:
        match = effective_pattern.search(paragraph)

        if match:
            return match.group(1).strip()

    return ""

In [50]:
# Test effective-date extraction
effective_date = get_effective_date(test_paragraphs)

print("Effective date:", effective_date or "Not found")

Effective date: February 15 2019

In [51]:
# Extract an Article by its heading, regardless of Article number.
def get_article_content(paragraphs: list,
                        heading_keywords: list) -> str:

    next_heading = re.compile(
        r"^(Article|Chapter|Section)\s+",
        flags=re.IGNORECASE)

    for index, paragraph in enumerate(paragraphs):
        is_article = re.match(r"^Article\s+\d+", paragraph,
                              flags=re.IGNORECASE)

        has_keyword = any(keyword.lower() in paragraph.lower()
                          for keyword in heading_keywords)

        if is_article and has_keyword:
            content = []

            # Collect content until the next Article, Chapter or Section
            for next_paragraph in paragraphs[index + 1:]:
                if next_heading.match(next_paragraph):
                    break

                content.append(next_paragraph)

            return " ".join(content)

    return ""

# Extract scope regardless of its Article number.
def get_scope(paragraphs: list) -> str:

    return get_article_content(
               paragraphs=paragraphs,
               heading_keywords=["scope", "governing scope"])

# Extract regulated entities regardless of their Article number.
def get_regulated_entities(paragraphs: list) -> str:

    return get_article_content(
               paragraphs=paragraphs,
               heading_keywords=["regulated entities",
                                 "subjects of application"])

In [52]:
# Test scope and regulated-entity extraction
print("Scope:")
print(get_scope(test_paragraphs))

print("\nRegulated entities:")
print(get_regulated_entities(test_paragraphs))

Scope:
This Decree stipulates the tasks, power, organization, equipment for operating and benefits for forest rangers and tasks, power, equipment for operating and benefits for forest protection forces of forest owners.

Regulated entities:
This Decree applies to forest rangers, forest protection forces of forest owners and agencies, organizations, individuals related to the activities thereof.

In [53]:
def classify_esg(body_text: str) -> tuple:
    """Suggest ESG labels using the approved taxonomy categories."""

    normalized_text = body_text.lower()
    matched_paths = []

    for keyword, domain, group, category in ESG_CLASSIFICATION_PATHS:
        if keyword in normalized_text:
            matched_paths.append({
                "domain": domain,
                "group": group,
                "category": category,
                "keyword": keyword
            })

    domains = sorted({match["domain"] for match in matched_paths})
    groups = sorted({match["group"] for match in matched_paths})
    categories = sorted({match["category"] for match in matched_paths})

    return domains, groups, categories, matched_paths

In [54]:
# Test ESG suggestions and inspect the evidence
test_text = "\n".join(test_paragraphs)

domains, groups, categories, matched_paths = classify_esg(test_text)

print("Domains:", domains)
print("Groups:", groups)
print("Categories:", categories)
display(pd.DataFrame(matched_paths))

Domains: ['Environment', 'Governance', 'Social']
Groups: ['Biodiversity', 'Corporate Governance, Strategy and Sustainability', 'Human Rights', 'Sustainable Production']
Categories: ['Biodiversity', 'Board', 'Diversity', 'Forests', 'Water']

,domain,group,category,keyword
0,Environment,Biodiversity,Biodiversity,biodiversity
1,Environment,Biodiversity,Forests,forests
2,Environment,Sustainable Production,Water,water
3,Social,Human Rights,Diversity,diversity
4,Governance,"Corporate Governance, Strategy and Sustainability",Board,board

In [55]:
# Clean extracted text while preserving substantive legal content.
def clean_body(paragraphs: list,
               body_start: int = 0) -> str:

    cleaned_paragraphs = []

    for paragraph in paragraphs[body_start:]:
        # Remove BOM and normalize whitespace
        cleaned_paragraph = paragraph.replace("\ufeff", "")
        cleaned_paragraph = " ".join(cleaned_paragraph.split()).strip()

        if not cleaned_paragraph:
            continue

        # Remove only verified boilerplate
        if cleaned_paragraph.upper() in BOILERPLATE:
            continue

        # Remove decorative separator lines
        if re.fullmatch(r"[-–—]{5,}", cleaned_paragraph):
            continue

        # Remove the translation-provider footer
        if "THƯ VIỆN PHÁP LUẬT" in cleaned_paragraph.upper():
            continue

        cleaned_paragraphs.append(cleaned_paragraph)

    return "\n".join(cleaned_paragraphs)

In [56]:
# Clean the document while preserving its title and preamble
cleaned_text = clean_body(paragraphs=test_paragraphs,
                          body_start=0)

print(cleaned_text[:2000])
print("\nWord count:", len(cleaned_text.split()))

TABLE ROW | THE GOVERNMENT-------- | SOCIALIST REPUBLIC OF VIETNAMIndependence – Freedom - Happiness---------------
TABLE ROW | No: 01/2019/ND-CP | Hanoi, January 01 2019
DECREE
ON FOREST RANGERS AND FOREST PROTECTION FORCES OF FOREST OWNERS
Pursuant to Law on the Government organization dated June 19 2015;
Pursuant to Law on Forestry dated November 15 2017;
At the proposal of the Minister of Natural Resources and Environment;
The Government promulgates a Decree on forest rangers and forest protection forces of forest owners.
Chapter I.
GENERAL PROVISIONS
Article 1. Scope
This Decree stipulates the tasks, power, organization, equipment for operating and benefits for forest rangers and tasks, power, equipment for operating and benefits for forest protection forces of forest owners.
Article 2. Regulated entities
This Decree applies to forest rangers, forest protection forces of forest owners and agencies, organizations, individuals related to the activities thereof.
Chapter II.
TASKS, POWER, ORGANIZATION, AND BENEFITS FOR FOREST RANGERS
Section 1: TASKS AND POWER OF FOREST RANGERS
Article 3: Tasks and power of the central forest ranger organizations
1. Advising the head of the agency to assist the Minister of Agriculture and Rural Development in performing the governmental management of forestry and formulating programs, plans for forest protection and management, forest fire safety, ensuring the compliance with law on forestry.
2. Directing, guiding and examining the performance of forest management, protection and forest fire safety, prevention and control of violations and ensuring the implementation of law on forestry nationwide as follows:
a) Organize implementation of legislative documents, programs, plans for forest management, protection, fire safety and ensuring the compliance with law on forestry.
b) Inspecting the development of forest, stocktaking, allocating, leasing, withdrawing, converting and repurposing forest;
c) Organize prevention of violations aga

Word count: 3727

##### **Main extraction loop**

In [57]:
# Main loop extraction 
# Extract cleaned text and metadata from all included documents.
def extract_all(docx_folder: Path, cleaned_text_folder: Path,
                log_folder: Path, document_type_lookup: dict) -> list:

    # Create the required output folders
    cleaned_text_folder.mkdir(parents=True, exist_ok=True)
    log_folder.mkdir(parents=True, exist_ok=True)

    # Include subfolders and exclude manually rejected files
    files = sorted(path for path in docx_folder.rglob("*.docx")
                   if path.name not in EXCLUDED_FILES)

    registry = []

    print(f"Extracting {len(files)} documents...\n")

    for number, path in enumerate(files, start=1):
        try:
            # Extract paragraphs and table rows
            paragraphs = get_paragraphs(path)

            if not paragraphs:
                registry.append({
                    "doc_id": path.stem,
                    "source_filename": path.name,
                    "status": "empty",
                    "error": None
                })

                print(f"[{number}/{len(files)}] EMPTY | {path.name}")
                continue

            # Use the manually verified corpus type when available
            document_type = document_type_lookup.get(path.name)

            if document_type:
                type_source = (
                    "manual_override"
                    if path.name in MANUAL_TYPE_OVERRIDES
                    else "document_heading"
                )
            else:
                document_type, type_source = get_document_type(
                                                 paragraphs=paragraphs,
                                                 filename=path.name)

            # Preserve the title and legal preamble in the cleaned text
            cleaned_text = clean_body(paragraphs=paragraphs,
                                      body_start=0)

            # Generate ESG suggestions for later manual verification
            domains, groups, categories, matched_paths = classify_esg(
                                                             cleaned_text)

            # Save one cleaned text file per document
            cleaned_path = cleaned_text_folder / f"{path.stem}.txt"
            cleaned_path.write_text(cleaned_text, encoding="utf-8")

            # Store document metadata
            metadata = {
                "doc_id": path.stem,
                "official_number": get_official_number(path.name),
                "document_type": document_type,
                "document_type_source": type_source,
                "document_type_code": get_doc_code(path.name),
                "title": get_title(paragraphs),
                "issuing_body": get_issuing_body(paragraphs),
                "issue_date": get_issue_date(paragraphs),
                "effective_date": get_effective_date(paragraphs),
                "scope": get_scope(paragraphs),
                "regulated_entities": get_regulated_entities(paragraphs),
                "esg_domains": domains,
                "esg_category_groups": groups,
                "esg_categories": categories,
                "esg_matches": matched_paths,
                "esg_review_status": "pending",
                "source_filename": path.name,
                "cleaned_path": str(cleaned_path),
                "word_count": len(cleaned_text.split()),
                "char_count": len(cleaned_text),
                "table_row_count": sum(
                    text.startswith("TABLE ROW |")
                    for text in paragraphs
                ),
                "status": "ok",
                "error": None
            }

            registry.append(metadata)

            esg_label = "/".join(domains) if domains else "unclassified"

            print(f"[{number}/{len(files)}] {document_type:20} | "
                  f"{metadata['word_count']:6} words | "
                  f"{metadata['table_row_count']:4} table rows | "
                  f"{esg_label} | {path.name}")

        except Exception as error:
            registry.append({
                "doc_id": path.stem,
                "source_filename": path.name,
                "status": "error",
                "error": str(error)
            })

            print(f"[{number}/{len(files)}] ERROR | "
                  f"{path.name} | {error}")

    # Save the complete metadata registry
    registry_path = log_folder / "corpus_registry.json"
    registry_path.write_text(
        json.dumps(registry, indent=2, ensure_ascii=False),
        encoding="utf-8")

    successful = sum(item["status"] == "ok"
                     for item in registry)

    empty = sum(item["status"] == "empty"
                for item in registry)

    errors = sum(item["status"] == "error"
                 for item in registry)

    print("\n" + "=" * 55)
    print("Documents processed:", len(registry))
    print("Successful:         ", successful)
    print("Empty:              ", empty)
    print("Errors:             ", errors)
    print("Registry:           ", registry_path)
    print("=" * 55)

    return registry

In [58]:
# Use document types already checked and manually corrected
document_type_lookup = (
    included_document_types
    .set_index("filename")["observed_type"]
    .to_dict()
)

In [59]:
# Extract cleaned text and metadata from all included documents
# registry = extract_all(docx_folder=CONVERTED_DOCX_FOLDER,
                       # cleaned_text_folder=CLEANED_TEXT_FOLDER,
                       # log_folder=LOG_FOLDER,
                       # document_type_lookup=document_type_lookup)

In [ ]:
# Load completed extraction unless reprocessing is explicitly requested

REGISTRY_PATH = LOG_FOLDER / "extraction_registry.json"
FORCE_REEXTRACT = False

if REGISTRY_PATH.exists() and not FORCE_REEXTRACT:
    registry = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    missing_outputs = [item for item in registry if item.get("status") == "ok"
                       and (not item.get("cleaned_path") or not Path(item["cleaned_path"]).exists())]

    if not missing_outputs:
        print(f"Extraction already completed — loaded {len(registry)} records.")
        print("Registry:", REGISTRY_PATH)
    else:
        print(f"{len(missing_outputs)} cleaned files are missing — running extraction.")
        registry = extract_all(docx_folder=CONVERTED_DOCX_FOLDER,
                               cleaned_text_folder=CLEANED_TEXT_FOLDER,
                               log_folder=LOG_FOLDER,
                               document_type_lookup=document_type_lookup)
else:
    registry = extract_all(docx_folder=CONVERTED_DOCX_FOLDER,
                           cleaned_text_folder=CLEANED_TEXT_FOLDER,
                           log_folder=LOG_FOLDER,
                           document_type_lookup=document_type_lookup)

registry_df = pd.DataFrame(registry)

Extracting 406 documents...

[1/406] Decree               |   3727 words |    3 table rows | Environment/Governance/Social | 01_2019_ND-CP_m_420475.docx
[2/406] Circular             |  21348 words |  286 table rows | Environment/Social | 01_2021_TT-BXD_m_488637.docx
[3/406] Decision             |    793 words |   31 table rows | Environment | 01_2022_QD-TTg_m_567258.docx
[4/406] Circular             |  16278 words |  584 table rows | Environment/Governance/Social | 01_2022_TT-BNNPTNT_m_511704.docx
[5/406] Circular             |   4745 words |    3 table rows | Environment/Social | 01_2022_TT-BTNMT_m_528824.docx
[6/406] Circular             |   4179 words |    3 table rows | Environment | 01_2024_TT-BKHCN_600112.docx
[7/406] Circular             |   8561 words |  139 table rows | Environment | 01_2025_TT-BNNMT_m_659004.docx
[8/406] Circular             |  11588 words |    3 table rows | Environment | 01_2026_TT-BNNMT_m_693953.docx
[9/406] Circular             |   1491 words |   14 table rows | Environment | 02_2022_TT-BTC_m_528882.docx
[10/406] Circular             |  29722 words |  131 table rows | Environment/Governance/Social | 02_2022_TT-BTNMT_m_507651.docx
[11/406] Circular             |   3591 words |    3 table rows | unclassified | 02_2025_TT-BCT_m_648178.docx
[12/406] Circular             |   3531 words |   50 table rows | Environment | 02_2025_TT-BTNMT_m_655384.docx
[13/406] Law                  |  15911 words |    3 table rows | Environment/Governance/Social | 02_2026_QH16_m_706740.docx
[14/406] Decree               |  29030 words |    3 table rows | Environment/Governance/Social | 02_VBHN-BKHCN_m_583353.docx
[15/406] Decree               |   8697 words |    3 table rows | Environment/Governance | 02_VBHN-BXD_m_613835.docx
[16/406] Circular             |   9356 words |    4 table rows | Governance | 03_2017_TT-BTNMT_m_349874.docx
[17/406] Decree               |  15991 words |    3 table rows | Environment/Governance/Social | 03_2022_ND-CP_m_504828.docx
[18/406] Circular             |   9574 words |    3 table rows | Environment/Social | 03_2024_TT-BTNMT_m_614092.docx
[19/406] Circular             |   2421 words |   97 table rows | Social | 03_2024_TT-BYT_m_607111.docx
[20/406] Circular             |   1313 words |    3 table rows | unclassified | 03_2025_TT-BLDTBXH_m_646590.docx
[21/406] Circular             |  18773 words |  235 table rows | Environment | 03_2026_TT-BNNMT_m_696487.docx
[22/406] Directive            |   1430 words |    3 table rows | Governance | 03_CT-NHNN_m_348086.docx
[23/406] Circular             |   4690 words |    7 table rows | Environment | 04_2015_TT-BXD_m_272760.docx
[24/406] Circular             |   1788 words |   34 table rows | Environment/Governance | 04_2016_TT-BTNMT_m_316899.docx
[25/406] Decision             |   1134 words |    3 table rows | Environment | 04_2017_QD-TTg_m_346090.docx
[26/406] Law                  |   4724 words |    3 table rows | Governance | 04_2017_QH14_m_359399.docx
[27/406] Circular             |   4468 words |   49 table rows | Governance | 04_2018_TT-BNNPTNT_m_519819.docx
[28/406] Circular             |    720 words |    3 table rows | unclassified | 04_2021_TT-BCT_m_482504.docx
[29/406] Decree               |  20937 words |   10 table rows | Environment/Governance | 04_2022_ND-CP_m_526056.docx
[30/406] Circular             |   2084 words |  132 table rows | unclassified | 04_2023_TT-BNNPTNT_m_576528.docx
[31/406] Circular             |   6545 words |    3 table rows | Environment | 04_2024_TT-BTNMT_m_611481.docx
[32/406] Circular             |   2632 words |   29 table rows | Environment | 04_2025_TT-BTNMT_m_647846.docx
[33/406] Decision             |  10309 words |    3 table rows | Environment | 04_2026_QD-TTg_m_695772.docx
[34/406] Circular             |   4885 words |    3 table rows | Environment/Social | 04_2026_TT-BNNMT_m_703639.docx
[35/406] Law                  |  11035 words |    3 table rows | Environment | 05_2007_QH12_m_85253.docx
[36/406] Circular             |   1741 words |    3 table rows | unclassified | 05_2015_TT-BNNPTNT_m_284118.docx
[37/406] Circular             |   4586 words |  257 table rows | Environment/Governance | 05_2023_TT-BLDTBXH_m_571572.docx
[38/406] Decree               |  56360 words |  288 table rows | Environment/Governance/Social | 05_2025_ND-CP_642709.docx
[39/406] Circular             |   4420 words |   84 table rows | Environment | 05_2025_TT-BTNMT_m_647847.docx
[40/406] Circular             |   5663 words |    3 table rows | Environment | 06_2020_TT-BKHCN_m_462602.docx
[41/406] Decree               |  10858 words |    3 table rows | Environment | 06_2022_ND-CP_m_503148.docx
[42/406] Circular             |   1906 words |   11 table rows | unclassified | 06_2025_TT-BNNMT_m_671280.docx
[43/406] Law                  |  11988 words |    3 table rows | Environment/Governance/Social | 07_2017_QH14_m_355880.docx
[44/406] Decree               |  20072 words |    3 table rows | Environment/Governance | 07_2022_ND-CP_m_504176.docx
[45/406] Circular             |   1147 words |   17 table rows | unclassified | 07_2023_TT-BTC_m_556248.docx
[46/406] Circular             |   1033 words |    8 table rows | Environment | 07_2024_TT-BTC_m_599643.docx
[47/406] Circular             |  12135 words |  133 table rows | Environment/Social | 07_2025_TT-BTNMT_m_647200.docx
[48/406] Circular             |   7434 words |    3 table rows | unclassified | 07_2026_TT-BNNMT_703640.docx
[49/406] Decree               |  30785 words |    3 table rows | Environment/Governance/Social | 08_2015_ND-CP_m_267759.docx
[50/406] Law                  |  13232 words |    3 table rows | Environment/Governance/Social | 08_2017_QH14_m_358520.docx
[51/406] Decision             |   1405 words |    3 table rows | Environment | 08_2020_QD-TTg_m_444837.docx
[52/406] Decree               |  81535 words |    4 table rows | Environment/Governance/Social | 08_2022_ND-CP_m_507203.docx
[53/406] Circular             |    891 words |    8 table rows | Governance | 08_2024_TT-BTC_m_598993.docx
[54/406] Circular             |   3326 words |    3 table rows | Environment | 08_2025_TT-BNNMT_m_666356.docx
[55/406] Circular             |   1716 words |    3 table rows | Environment | 08_2025_TT-BYT_m_648862.docx
[56/406] Circular             |   6975 words |    3 table rows | Environment/Governance/Social | 08_2026_TT-BNNMT_m_700097.docx
[57/406] Law                  |  24456 words |    3 table rows | Environment/Governance | 08_VBHN-VPQH_m_651938.docx
[58/406] Circular             |   3169 words |   38 table rows | unclassified | 09_2009_TT-BKHCN_m_199506.docx
[59/406] Circular             |   4003 words |    7 table rows | Environment | 09_2020_TT-BLDTBXH_m_469628.docx
[60/406] Circular             |   8837 words |    3 table rows | Environment/Governance | 09_2025_TT-BNNMT_m_715473.docx
[61/406] Circular             |   8385 words |  147 table rows | Environment/Governance | 09_2025_TT-BYT_m_658051.docx
[62/406] Circular             |  13555 words |    3 table rows | Environment/Governance/Social | 09_2026_TT-BNNMT_m_696445.docx
[63/406] Circular             |  10363 words |    3 table rows | Environment/Social | 09_VBHN-BNNMT_m_696385.docx
[64/406] Decision             |    432 words |    3 table rows | unclassified | 1009_QD-BCT_m_656831.docx
[65/406] Decree               |   3312 words |    5 table rows | Environment | 100_2016_ND-CP_m_318912.docx
[66/406] Circular             |   1705 words |    3 table rows | Environment | 100_2020_TT-BTC_m_459277.docx
[67/406] Decree               |    714 words |    3 table rows | Environment | 100_2025_ND-CP_m_659917.docx
[68/406] Integrated Document  |  50517 words |    3 table rows | Environment/Governance/Social | 101_VBHN-VPQH_m_694902.docx
[69/406] Decree               |   9775 words |   88 table rows | Environment/Governance/Social | 102_2020_ND-CP_m_453730.docx
[70/406] Decision             |   8750 words |   52 table rows | Environment/Social | 1055_QD-UBND_m_487758.docx
[71/406] Decree               |   3568 words |    3 table rows | Environment/Governance/Social | 105_2015_ND-CP_m_294263.docx
[72/406] Decree               |  31359 words |  245 table rows | Environment/Governance | 105_2025_ND-CP_m_660034.docx
[73/406] Law                  |   1880 words |   36 table rows | Environment | 106_2016_QH13_m_311054.docx
[74/406] Decree               |  10777 words |    3 table rows | Environment/Governance/Social | 106_2025_ND-CP_m_658555.docx
[75/406] Decree               |   5017 words |    3 table rows | Environment | 107_2022_ND-CP_581407.docx
[76/406] Decree               |    557 words |    9 table rows | Environment | 108_2025_ND-CP_m_658466.docx
[77/406] Ordinance            |   1513 words |    3 table rows | unclassified | 10_2014_UBTVQH13_m_267874.docx
[78/406] Circular             |   4835 words |    3 table rows | Environment/Governance/Social | 10_2020_TT-BLDTBXH_m_463446.docx
[79/406] Circular             |   2495 words |    3 table rows | unclassified | 10_2021_TT-BKHDT_m_502913.docx
[80/406] Circular             |   1677 words |   24 table rows | Environment | 10_2024_TT-BTC_m_599777.docx
[81/406] Circular             |   2603 words |    3 table rows | Environment/Governance | 10_2025_TT-BCT_m_654921.docx
[82/406] Decree               |  17528 words |    3 table rows | Environment | 10_VBHN-BNNMT_m_669553.docx
[83/406] Decree               |   9254 words |   78 table rows | Environment | 110_2026_ND-CP_702140.docx
[84/406] Circular             |    998 words |    7 table rows | unclassified | 112_2021_TT-BTC_m_529021.docx
[85/406] Decree               |  10992 words |   66 table rows | Environment/Governance | 112_2026_ND-CP_701500.docx
[86/406] Circular             |   2868 words |    3 table rows | unclassified | 115_2014_TT-BTC_m_283734.docx
[87/406] Decree               |   3056 words |    3 table rows | unclassified | 116_2014_ND-CP_m_261978.docx
[88/406] Decree               |   4043 words |   88 table rows | unclassified | 116_2018_ND-CP_m_397485.docx
[89/406] Law                  |  13728 words |    3 table rows | Environment/Social | 116_2025_QH15_m_688491.docx
[90/406] Law                  |  18295 words |    4 table rows | Environment | 116_VBHN-VPQH_m_674551.docx
[91/406] Decree               |  10127 words |    3 table rows | Environment/Governance | 117_2007_ND-CP_m_85846.docx
[92/406] Decree               |  16034 words |    3 table rows | Environment/Governance/Social | 119_2017_ND-CP_m_372479.docx
[93/406] Decree               |  33360 words |  669 table rows | Environment/Social | 119_2025_ND-CP_m_661711.docx
[94/406] Order                |    140 words |    3 table rows | unclassified | 11_2001_L-CTN_m_71892.docx
[95/406] Decree               |  10226 words |    3 table rows | Environment/Governance | 11_2013_ND-CP_m_171210.docx
[96/406] Circular             |  53513 words | 1984 table rows | Environment/Governance | 11_2020_TT-BLDTBXH_m_471610.docx
[97/406] Circular             |   2827 words |    3 table rows | Environment | 11_2022_TT-BTNMT_m_548219.docx
[98/406] Circular             |   5448 words |  207 table rows | Environment/Governance | 11_2024_TT-BTC_m_600179.docx
[99/406] Decision             |   5242 words |    3 table rows | Environment | 11_2025_QD-TTg_m_655230.docx
[100/406] Circular             |   7575 words |    3 table rows | Governance | 11_2026_TT-BNNMT_m_699086.docx
[101/406] Circular             |   5234 words |    6 table rows | Environment/Social | 11_VBHN-BNNMT_m_666359.docx
[102/406] Integrated Document  |   3871 words |    5 table rows | Environment | 11_VBHN-BTC_m_609280.docx
[103/406] Decree               |   3415 words |    3 table rows | Environment/Governance/Social | 120_2024_ND-CP_m_627703.docx
[104/406] Decree               |   4798 words |    3 table rows | Environment | 123_2018_ND-CP_m_396523.docx
[105/406] Decree               |   1183 words |    3 table rows | Environment | 124_2011_ND-CP_m_134023.docx
[106/406] Integrated Document  |  29368 words |    3 table rows | Environment/Governance/Social | 125_VBHN-VPQH_m_682303.docx
[107/406] Circular             |   1119 words |    3 table rows | Environment | 12_2021_TT-BNNPTNT_m_497304.docx
[108/406] Decree               |  29337 words |    3 table rows | Governance/Social | 12_2022_ND-CP_m_508088.docx
[109/406] Circular             |    838 words |    3 table rows | unclassified | 12_2022_TT-BCT_m_582930.docx
[110/406] Circular             |   1045 words |    3 table rows | Governance | 12_2024_TT-BTC_m_599080.docx
[111/406] Law                  |   2684 words |    3 table rows | Environment | 130_VBHN-VPQH_m_673702.docx
[112/406] Circular             |   3454 words |    3 table rows | Environment/Governance/Social | 132_2015_TT-BTC_m_291239.docx
[113/406] Decision             |   2674 words |    9 table rows | Environment | 1336_QD-TTg_m_83813.docx
[114/406] Decree               |  15121 words |    3 table rows | Environment/Governance/Social | 133_2026_ND-CP_m_713070.docx
[115/406] Decree               |  14895 words |  104 table rows | Environment/Governance | 134_2016_ND-CP_m_326662.docx
[116/406] Law                  |   6763 words |    3 table rows | Environment/Governance/Social | 134_2025_QH15_m_689735.docx
[117/406] Law                  |  23751 words |  243 table rows | Environment/Governance/Social | 134_VBHN-VPQH_m_676210.docx
[118/406] Decision             |   4103 words |   17 table rows | Environment/Governance | 1362_QD-TTg_m_427551.docx
[119/406] Decree               |   2978 words |    3 table rows | Environment/Governance | 136_2018_ND-CP_m_398653.docx
[120/406] Resolution           |  15012 words |   47 table rows | Environment/Governance/Social | 138_NQ-CP_m_544532.docx
[121/406] Circular             |   5240 words |    3 table rows | Environment | 13_2012_TT-BTC_m_139901.docx
[122/406] Circular             |  14381 words |    4 table rows | Environment/Governance | 13_2016_TT-BNNPTNT_m_318472.docx
[123/406] Circular             |   8712 words |    3 table rows | Environment | 13_2021_TT-BNNPTNT_m_495964 (1).docx
[124/406] Circular             |   8712 words |    3 table rows | Environment | 13_2021_TT-BNNPTNT_m_495964.docx
[125/406] Decision             |    620 words |    3 table rows | Environment | 13_2024_QD-TTg_m_630930.docx
[126/406] Decision             |   1587 words |    3 table rows | Governance | 13_2026_QD-TTg_m_704071.docx
[127/406] Circular             |   3435 words |   31 table rows | Environment | 13_2026_TT-BXD_m_705617.docx
[128/406] Decree               |    442 words |    3 table rows | unclassified | 144_2024_ND-CP_m_647300.docx
[129/406] Decree               |  27594 words |   30 table rows | Environment/Governance/Social | 145_2020_ND-CP_m_461788.docx
[130/406] Law                  |  32198 words |    3 table rows | Environment/Governance/Social | 146_2025_QH15_706223.docx
[131/406] Decision             |   5975 words |    9 table rows | Environment | 146_QD-TTg_m_570574.docx
[132/406] Decision             |   4862 words |    3 table rows | Environment/Governance/Social | 1474_QD-TTg_m_182078.docx
[133/406] Law                  |   8495 words |    3 table rows | Environment/Governance/Social | 148_2025_QH15_m_689736.docx
[134/406] Circular             |   1645 words |    3 table rows | Governance | 14_2018_TT-NHNN_m_384350.docx
[135/406] Circular             |   1012 words |   25 table rows | unclassified | 14_2023_TT-BNNPTNT_m_594179.docx
[136/406] Circular             |    872 words |    3 table rows | Environment | 14_2024_TT-BNNPTNT_m_645312.docx
[137/406] Decree               |   8323 words |    3 table rows | Governance/Social | 152_2020_ND-CP_m_461585.docx
[138/406] Decree               |   3571 words |    9 table rows | Environment | 153_2024_ND-CP_m_635652.docx
[139/406] Decree               |   6703 words |   55 table rows | Environment | 154_2018_ND-CP_m_403097.docx
[140/406] Decree               |   2065 words |    3 table rows | Social | 156_2025_ND-CP_m_662760.docx
[141/406] Law                  |  11780 words |    4 table rows | Environment/Governance/Social | 159_VBHN-VPQH_m_676505.docx
[142/406] Law                  |  22697 words |    3 table rows | Environment/Governance | 15_2017_QH14_m_381270.docx
[143/406] Decree               |  13086 words |  203 table rows | Environment | 15_2018_ND-CP_375807.docx
[144/406] Circular             |   1033 words |    3 table rows | Environment | 15_2021_TT-BNNPTNT_m_500542.docx
[145/406] Circular             |   1820 words |    3 table rows | Environment | 15_2021_TT-BXD_m_501533.docx
[146/406] Circular             |   3889 words |    3 table rows | unclassified | 15_2022_TT-BNNPTNT_m_536367.docx
[147/406] Circular             |   2617 words |    3 table rows | unclassified | 15_2024_TT-BNNPTNT_m_635285.docx
[148/406] Law                  |   5206 words |    3 table rows | Environment/Governance | 15_VBHN-VPQH_m_636777.docx
[149/406] Decision             |   5708 words |    3 table rows | Environment/Governance | 1658_QD-TTg_m_549600.docx
[150/406] Decree               |   9501 words |    3 table rows | Environment/Social | 165_2025_ND-CP_m_664591.docx
[151/406] Decision             |   8715 words |  156 table rows | Environment/Governance | 1679_QD-BGTVT_m_594491.docx
[152/406] Decision             |   2123 words |    3 table rows | Environment/Governance | 167_QD-TTg_m_519257.docx
[153/406] Decision             |   4583 words |    3 table rows | Environment/Governance/Social | 1690_QD-TTg_m_114738.docx
[154/406] Decision             |  11903 words |  243 table rows | Environment/Governance | 16_2008_QD-BTNMT_m_151123.docx
[155/406] Law                  |  19698 words |   71 table rows | Environment/Governance/Social | 16_2023_QH15_m_576363.docx
[156/406] Circular             |  20753 words | 1066 table rows | Environment | 16_2026_TT-BNNMT_m_699954.docx
[157/406] Decision             |   2702 words |   12 table rows | Environment/Governance | 170_QD-TTg_m_138627.docx
[158/406] Decision             |   2537 words |    3 table rows | Environment/Governance/Social | 1746_QD-TTg_m_431613.docx
[159/406] Circular             |   4942 words |   56 table rows | Environment/Governance/Social | 17_2016_TT-BKHCN_m_427233.docx
[160/406] Circular             |   8761 words |  261 table rows | Environment/Governance | 17_2019_TT-BLDTBXH_m_429595.docx
[161/406] Decree               |  39586 words |    3 table rows | Environment/Governance/Social | 17_2022_ND-CP_m_509987.docx
[162/406] Circular             |   3298 words |    3 table rows | Environment | 17_2022_TT-BNNPTNT_m_536827.docx
[163/406] Circular             |   4039 words |    3 table rows | Environment | 17_2022_TT-BTNMT_m_550994.docx
[164/406] Circular             |   1108 words |    3 table rows | unclassified | 17_2022_TT-NHNN_m_548392.docx
[165/406] Circular             |    879 words |    3 table rows | unclassified | 17_2026_TT-BNNMT_m_703611.docx
[166/406] Decree               |   6661 words |    3 table rows | Environment/Governance/Social | 180_2026_ND-CP_m_712397.docx
[167/406] Decree               |  18213 words |    9 table rows | Environment/Governance/Social | 181_2025_ND-CP_m_665245.docx
[168/406] Resolution           |   2756 words |    3 table rows | Environment/Governance | 189_2025_QH15_m_653665.docx
[169/406] Circular             |   2906 words |    3 table rows | Environment/Governance | 18_2022_TT-BNNPTNT_m_544831.docx
[170/406] Law                  |   9890 words |    3 table rows | Environment/Governance/Social | 18_2023_QH15_573754.docx
[171/406] Decree               |   2481 words |   20 table rows | unclassified | 18_2025_ND-CP_m_650598.docx
[172/406] Integrated Document  |  29385 words |    3 table rows | Environment/Governance/Social | 18_VBHN-VPQH_m_699248.docx
[173/406] Decree               |  54555 words |    3 table rows | Environment/Governance | 193_2025_ND-CP_m_673825.docx

In [63]:
# Check source files, cleaned files and registry records
docx_files = list(CONVERTED_DOCX_FOLDER.rglob("*.docx"))
cleaned_files = list(CLEANED_TEXT_FOLDER.rglob("*.txt"))

print("Converted .docx files:", len(docx_files))
print("Cleaned .txt files:   ", len(cleaned_files))
print("Registry records:     ", len(registry))
print("Successful records:   ", sum(item.get("status") == "ok" for item in registry))
print("Empty records:        ", sum(item.get("status") == "empty" for item in registry))
print("Error records:        ", sum(item.get("status") == "error" for item in registry))

Converted .docx files: 407
Cleaned .txt files:    406
Registry records:      406
Successful records:    406
Empty records:         0
Error records:         0

#### **Validate final results**

In [64]:
# Convert the registry into a table for validation
registry_df = pd.DataFrame(registry)

print("Expected documents:", len(included_document_types))
print("Registry documents:", len(registry_df))
print("Successful:",
      (registry_df["status"] == "ok").sum())
print("Errors:",
      (registry_df["status"] == "error").sum())

Expected documents: 406
Registry documents: 406
Successful: 406
Errors: 0

In [65]:
# Display the document that failed during extraction
error_files = registry_df[
    registry_df["status"] == "error"]

display(error_files[[
    "source_filename",
    "doc_id",
    "error"]])

Empty DataFrame
Columns: [source_filename, doc_id, error]
Index: []

In [66]:
# Test the repaired table extraction on the failed document
ERROR_TEST_FILE = (
    CONVERTED_DOCX_FOLDER
    / "70_2023_ND-CP_m_580154.docx"
)

error_test_content = get_paragraphs(ERROR_TEST_FILE)

print("Extracted blocks:", len(error_test_content))
print("Table rows:",
      sum(text.startswith("TABLE ROW |")
          for text in error_test_content))
print("Extraction successful:", len(error_test_content) > 0)

Extracted blocks: 318
Table rows: 104
Extraction successful: True

In [67]:
# Reprocess only the previously failed document
path = ERROR_TEST_FILE
paragraphs = get_paragraphs(path)

document_type = document_type_lookup.get(path.name, "Unknown")
cleaned_text = clean_body(paragraphs=paragraphs,
                          body_start=0)

domains, groups, categories, matches = classify_esg(cleaned_text)

# Save its cleaned text
cleaned_path = CLEANED_TEXT_FOLDER / f"{path.stem}.txt"
cleaned_path.write_text(cleaned_text, encoding="utf-8")

# Recreate its metadata
repaired_metadata = {"doc_id": path.stem,
                     "official_number": get_official_number(path.name),
                     "document_type": document_type,
                     "document_type_source": "document_heading",
                     "document_type_code": get_doc_code(path.name),
                     "title": get_title(paragraphs),
                     "issuing_body": get_issuing_body(paragraphs),
                     "issue_date": get_issue_date(paragraphs),
                     "effective_date": get_effective_date(paragraphs),
                     "scope": get_scope(paragraphs),
                     "regulated_entities": get_regulated_entities(paragraphs),
                     "esg_domains": domains,
                     "esg_category_groups": groups,
                     "esg_categories": categories,
                     "esg_matches": matches,
                     "esg_review_status": "pending",
                     "source_filename": path.name,
                     "cleaned_path": str(cleaned_path),
                     "word_count": len(cleaned_text.split()),
                     "char_count": len(cleaned_text),
                     "table_row_count": sum( text.startswith("TABLE ROW |") for text in paragraphs),
                     "status": "ok",
                     "error": None
}

In [68]:
# Find and replace the failed registry row
error_index = registry_df.index[
    registry_df["source_filename"] == path.name][0]

for column, value in repaired_metadata.items():
    registry_df.at[error_index, column] = value

In [69]:
# Confirm that all 406 documents now succeeded
print("Registry documents:", len(registry_df))
print("Successful:", (registry_df["status"] == "ok").sum())
print("Errors:", (registry_df["status"] == "error").sum())

Registry documents: 406
Successful: 406
Errors: 0

In [70]:
# Save the corrected complete registry
registry = registry_df.to_dict(orient="records")

registry_path = LOG_FOLDER / "corpus_registry.json"
registry_path.write_text(
    json.dumps(registry, indent=2, ensure_ascii=False),
    encoding="utf-8")

print("Updated registry:", registry_path)

Updated registry: /Users/tanggiee/Desktop/RAG_AI/esg_rag_project/outputs/logs/corpus_registry.json

In [73]:
# Find successful documents with no ESG domain assigned "unclassified"
unclassified_files = registry_df[(registry_df["status"] == "ok")
                                 & registry_df["esg_domains"].apply(
                                     lambda value: not isinstance(value, list) or len(value) == 0)].copy()

print("Unclassified files:", len(unclassified_files))

# Display the complete unclassified list
with pd.option_context("display.max_rows", None,
                       "display.max_colwidth", 120):
    display(unclassified_files[[
        "source_filename",
        "official_number",
        "document_type",
        "title"
    ]])

Unclassified files: 59

,source_filename,official_number,document_type,title
10,02_2025_TT-BCT_m_648178.docx,02/2025/TT-BCT,Circular,ON PROTECTION OF ELECTRICITY WORKS AND SAFETY IN ELECTRICAL SECTOR
19,03_2025_TT-BLDTBXH_m_646590.docx,03/2025/TT-BLDTBXH,Circular,ON WORK CLASSIFICATION STANDARDS BASED ON WORKING CONDITIONS
27,04_2021_TT-BCT_m_482504.docx,04/2021/TT-BCT,Circular,ON WORKING HOURS AND RESTING HOURS OF WORKERS WORKING IN UNDERGROUND MINES
29,04_2023_TT-BNNPTNT_m_576528.docx,04/2023/TT-BNNPTNT,Circular,PROMULGATING THE LIST OF LIVING THINGS SUBJECT TO PLANT QUARANTINE IN VIETNAM
35,05_2015_TT-BNNPTNT_m_284118.docx,05/2015/TT-BNNPTNT,Circular,REGULATIONS ON SEQUENCE AND PROCEDURES FOR ISSUANCE OF PRACTISING CERTIFICATE FOR TREATMENT OF PLANT QUARANTINE SUBJ...
41,06_2025_TT-BNNMT_m_671280.docx,06/2025/TT-BNNMT,Circular,ON NATIONAL TECHNICAL REGULATION ON EMISSIONS OF IN-USE AUTOMOBILES
44,07_2023_TT-BTC_m_556248.docx,07/2023/TT-BTC,Circular,"PRESCRIBING FEES FOR APPRAISAL OF ENVIRONMENTAL REMEDIATION AND IMPROVEMENT PLANS BY CENTRAL-LEVEL AUTHORITIES, COLL..."
47,07_2026_TT-BNNMT_703640.docx,07/2026/TT-BNNMT,Circular,"ELABORATING CERTAIN ARTICLES OF THE LAW ON PLANT PROTECTION AND QUARANTINE, LAW ON CROP CULTIVATION AND AMENDMENTS T..."
57,09_2009_TT-BKHCN_m_199506.docx,09/2009/TT-BKHCN,Circular,PROVIDING GUIDANCE ON THE REQUIREMENTS AND PROCEDURE FOR DESIGNATION OF CONFORMITY ASSESSMENT BODIES
63,1009_QD-BCT_m_656831.docx,1009/QD-BCT,Decision,APPROVING THE GENERATION PRICE BRACKET FOR COAL POWER PLANTS IN 2025
76,10_2014_UBTVQH13_m_267874.docx,10/2014/UBTVQH13,Ordinance,ENVIRONMENTAL POLICE FORCES
78,10_2021_TT-BKHDT_m_502913.docx,10/2021/TT-BKHDT,Circular,"GUIDING INTEGRATION OF NATURAL DISASTER PREVENTION WITH SECTOR, SOCIO-ECONOMIC DEVELOPMENT PLANNING AND PLANS"
83,112_2021_TT-BTC_m_529021.docx,112/2021/TT-BTC,Circular,"FEES AND CHARGES IN AQUACULTURE MANAGEMENT AND COLLECTION, SUBMISSION, MANAGEMENT, AND USE THEREOF"
85,115_2014_TT-BTC_m_283734.docx,115/2014/TT-BTC,Circular,"PROVIDING GUIDANCE ON THE INSURANCE POLICY STIPULATED IN THE GOVERNMENT'S DECREE No. 67/2014 / ND-CP DATED JULY 07, ..."
86,116_2014_ND-CP_m_261978.docx,116/2014/ND-CP,Decree,PROVIDING DETAILED INSTRUCTIONS ON THE IMPLEMENTATION OF SEVERAL ARTICLES OF THE LAW ON PLANT PROTECTION AND QUARANTINE
87,116_2018_ND-CP_m_397485.docx,116/2018/ND-CP,Decree,"AMENDING SEVERAL ARTICLES OF DECREE NO.55/2015/ND-CP DATED JUNE 09, 2015 OF THE GOVERNMRNT ON CREDIT POLICY FOR AGRI..."
93,11_2001_L-CTN_m_71892.docx,11/2001/L-CTN,Order,ON THE PROMULGATION OF THE ORDINANCE ON THE PLANT PROTECTION AND QUARANTINE
108,12_2022_TT-BCT_m_582930.docx,12/2022/TT-BCT,Circular,"WORKING HOURS, REST PERIODS FOR WORKERS OPERATING, MAINTAINING, REPAIRING GAS DISTRIBUTION PIPELINES AND GAS WORKS"
127,144_2024_ND-CP_m_647300.docx,144/2024/ND-CP,Decree,"AMENDING THE GOVERNMENT’S DECREE NO. 26/2023/ND-CP DATED MAY 31, 2023 ON SCHEDULES OF EXPORT TARIFFS AND PREFERENTIA..."
134,14_2023_TT-BNNPTNT_m_594179.docx,14/2023/TT-BNNPTNT,Circular,PROMULGATING LIST OF ANIMAL BREEDS TO BE IMPORTED
145,15_2022_TT-BNNPTNT_m_536367.docx,15/2022/TT-BNNPTNT,Circular,INSPECTION AND SUPERVISION OF VETERINARY HYGIENE AND FOOD SAFETY FOR HONEY
146,15_2024_TT-BNNPTNT_m_635285.docx,15/2024/TT-BNNPTNT,Circular,"AMENDMENTS TO SOME ARTICLES OF CIRCULAR NO. 09/2016/TT-BNNPTNT DATED JUNE 01, 2016 OF THE MINISTER OF AGRICULTURE AN..."
163,17_2022_TT-NHNN_m_548392.docx,17/2022/TT-NHNN,Circular,PROVIDING GUIDELINES ON ENVIRONMENTAL RISK MANAGEMENT IN CREDIT EXTENSION BY CREDIT INSTITUTIONS AND FOREIGN BANK BR...
164,17_2026_TT-BNNMT_m_703611.docx,17/2026/TT-BNNMT,Circular,"ON AMENDMENTS TO SOME ARTICLES OF CIRCULAR NO. 25/2018/TT-BNNPTNT DATED NOVEMBER 15, 2018 OF MINISTER OF AGRICULTURE..."
170,18_2025_ND-CP_m_650598.docx,18/2025/ND-CP,Decree,ELABORATING THE LAW ON ELECTRICITY RELATING TO ELECTRICITY TRADE AND ELECTRICITY SUPPLY CAPABILITY
174,199_2025_ND-CP_m_664759.docx,199/2025/ND-CP,Decree,"ON AMENDMENTS TO DECREE NO. 26/2023/ND-CP DATED MAY 31, 2023 OF THE GOVERNMENT ON SCHEDULE OF EXPORT TARIFFS, SCHEDU..."
175,19_2009_TT-BKHCN_m_96067.docx,19/2009/TT-BKHCN,Circular,ON QUALITY CONTROL MEASURES FOR PRODUCTS AND GOODS SUBJECT TO INCREASED MANAGEMENT BEFORE MARKET CIRCULATION
181,203_2025_QH15_m_661982.docx,203/2025/QH15,Resolution,AMENDMENTS TO CERTAIN ARTICLES OF THE CONSTITUTION OF THE SOCIALIST REPUBLIC OF VIETNAM
185,20_2009_TT-BXD_m_358651.docx,20/2009/TT-BXD,Circular,"ON AMENDMENTS TO THE CIRCULAR NO. 20/2005/TT-BXD DATED DECEMBER 20, 2005 BY THE MINISTRY OF CONSTRUCTION ON GUIDELIN..."
187,20_2023_QH15_m_577937.docx,20/2023/QH15,Law,ELECTRONIC TRANSACTIONS
188,20_2023_TT-BCT_m_587433.docx,20/2023/TT-BCT,Circular,WORKING HOURS AND REST PERIODS OF OFFSHORE PETROLEUM WORKERS
192,21_2025_ND-CP_m_647927.docx,21/2025/ND-CP,Decree,"AMENDMENTS TO ARTICLE 9 OF THE DECREE NO. 26/2023/ND-CP DATED MAY 31, 2023 OF THE GOVERNMENT OF VIETNAM ON SCHEDULE ..."
205,246_2016_TT-BTC_m_334309.docx,246/2016/TT-BTC,Circular,"ON THE RATE, COLLECTION, SUBMISSION, ADMINISTRATION AND USE OF THE FEES FOR EXAMINATION, ASSESSMENT AND INTERNATIONA..."
210,259_2016_TT-BTC_m_334312.docx,259/2016/TT-BTC,Circular,"ON THE RATE, COLLECTION, SUBMISSION, ADMINISTRATION AND USE OF THE FEE FOR AUTHENTICATION OF DOCUMENTS AND THE CHARG..."
214,25_2022_TT-BTTTT_m_555757.docx,25/2022/TT-BTTTT,Circular,"REGULATIONS ON DETERMINING IMPORTED MATERIALS, SUPPLIES AND COMPONENTS THAT ARE SUBJECT TO EXEMPTION FROM IMPORT TAR..."
215,25_2025_TT-BYT_m_669298.docx,25/2025/TT-BYT,Circular,"ON ELABORATION OF THE LAW ON SOCIAL INSURANCE LAW, THE LAW ON OCCUPATIONAL SAFETY AND HYGIENE IN THE HEALTH SECTOR, ..."
216,25_2026_TT-BYT_m_717485.docx,25/2026/TT-BYT,Circular,ON AMENDMENTS TO SOME ARTICLES OF CIRCULAR NO. 01/2013/TT-BYT GUIDING THE MANAGEMENT OF MEDICAL TESTING QUALITY AT M...
231,29_2023_QD-TTg_m_593520.docx,29/2023/QD-TTg,Decision,"ON APPLICATIONS AND PROCEDURES FOR DETERMINATION OF PROJECTS WITH OUTDATED TECHNOLOGY, POTENTIAL FOR ENVIRONMENTAL P..."
233,29_2026_ND-CP_m_696591.docx,29/2026/ND-CP,Decree,ON DOMESTIC CARBON EXCHANGE
253,34_2023_TT-BTC_m_568907.docx,34/2023/TT-BTC,Circular,PRESCRIBING FEES FOR APPRAISAL OF APPLICATIONS FOR CERTIFICATE OF ELIGIBILITY TO PROVIDE ENVIRONMENTAL MONITORING SE...
255,356_2025_ND-CP_689146.docx,356/2025/ND-CP,Decree,ELABORATING ON CERTAIN ARTICLES AND IMPLEMENTATION MEASURES OF LAW ON PERSONAL DATA PROTECTION
258,35_2024_TT-BYT_m_645668.docx,35/2024/TT-BYT,Circular,ON THE BASIC QUALITY STANDARDS OF HOSPITALS
270,37_2011_QD-TTg_m_126596.docx,37/2011/QD-TTg,Decision,ON THE MECHANISM SUPPORTING THE DEVELOPMENT OF WIND POWER PROJECT IN VIETNAM
289,42_2025_TT-BKHCN_m_686951.docx,42/2025/TT-BKHCN,Circular,APPLICATION OF STANDARDS AND TECHNICAL REGULATIONS TO DATA CENTERS
291,43_2024_QH15_m_618648.docx,43/2024/QH15,Law,"Amendments to certain Articles of Land Law No. 31/2024/QH15, Housing Law No. 27/2023/QH15, Law on Real Estate Busine..."
295,44_2018_TT-BTC_m_519044.docx,44/2018/TT-BTC,Circular,"AMENDMENTS TO THE CIRCULAR NO. 285/2016/TT-BTC DATED NOVEMBER 14, 2016 ON VETERINARY FEES, COLLECTION, TRANSFER AND ..."
305,46_2024_TT-BGTVT_m_645145.docx,46/2024/TT-BGTVT,Circular,"ON DOCUMENTATION, PROCEDURES FOR ISSUANCE, REISSUANCE, SUSPENSION, REVOCATION OF CERTIFICATES OF ELIGIBILITY TO COND..."
326,57_QD-TTg_m_102712.docx,57/QD-TTg,Decision,APPROVING THE PLACEMENT OF CULTURAL ATTACHES IN A NUMBER OF KEY FOREIGN COUNTRIES
332,60_2023_ND-CP_m_577202.docx,60/2023/ND-CP,Decree,ON TECHNICAL SAFETY QUALITY AND ENVIRONMENTAL PROTECTION INSPECTION AND CERTIFICATE OF CONFORMITY FROM INSPECTION FO...
339,63_NQ-CP_m_425673.docx,63/NQ-CP,Resolution,"PROMULGATING LIST OF PLANNINGS FOR INVESTMENT IN AND DEVELOPMENT OF SPECIFIC GOODS, SERVICES AND PRODUCTS, AND DETER..."
349,67_2021_TT-BTC_m_485532.docx,67/2021/TT-BTC,Circular,"PRESCRIBING FOOD SAFETY FEES AND COLLECTION, TRANSFER, MANAGEMENT AND USE THEREOF"
351,67_2025_TT-BNNMT_m_683464.docx,67/2025/TT-BNNMT,Circular,PROMULGATING NATIONAL TECHNICAL REGULATIONS ON AQUACULTURE FEED AND ENVIRONMENTAL TREATMENT PRODUCTS IN AQUACULTURE
367,75_2025_TT-BNNMT_m_687673.docx,75/2025/TT-BNNMT,Circular,PROMULGATING LISTS OF APPROVED AND PROHIBITED PLANT PROTECTION CHEMICALS IN VIETNAM
372,809_QD-TTg_m_127920.docx,809/QD-TTg,Decision,"APPROVING THE SCHEME ON IMPROVEMENT OF THE CAPACITY FOR QUALITY MANAGEMENT OF AGRICULTURAL, FORESTRY AND FISHERY PRO..."
378,85_2016_ND-CP_m_318857.docx,85/2016/ND-CP,Decree,ON THE SECURITY OF INFORMATION SYSTEMS BY CLASSIFICATION
383,87_2025_QH15_m_663144.docx,87/2025/QH15,Law,AMENDMENTS TO CERTAIN ARTICLES OF THE LAW ON PROMULGATION OF LEGISLATIVE DOCUMENTS
384,87_2025_TT-BNNMT_m_695423.docx,87/2025/TT-BNNMT,Circular,"ON PROCEDURES FOR SUBMITTING, RECEIVING, AND PROVIDING GEOLOGICAL AND MINERAL INFORMATION AND DATA"
392,91_2025_QH15_m_665440.docx,91/2025/QH15,Law,PERSONAL DATA PROTECTION
400,94_2025_TT-BNNMT_m_695179.docx,94/2025/TT-BNNMT,Circular,ELABORATING ON SEVERAL ARTICLES OF THE LAW ON ANIMAL HUSBANDRY

In [74]:
# Return the unclassified filenames as a Python list
unclassified_filename_list = unclassified_files["source_filename"].tolist()

print(unclassified_filename_list)

['02_2025_TT-BCT_m_648178.docx', '03_2025_TT-BLDTBXH_m_646590.docx', '04_2021_TT-BCT_m_482504.docx', '04_2023_TT-BNNPTNT_m_576528.docx', '05_2015_TT-BNNPTNT_m_284118.docx', '06_2025_TT-BNNMT_m_671280.docx', '07_2023_TT-BTC_m_556248.docx', '07_2026_TT-BNNMT_703640.docx', '09_2009_TT-BKHCN_m_199506.docx', '1009_QD-BCT_m_656831.docx', '10_2014_UBTVQH13_m_267874.docx', '10_2021_TT-BKHDT_m_502913.docx', '112_2021_TT-BTC_m_529021.docx', '115_2014_TT-BTC_m_283734.docx', '116_2014_ND-CP_m_261978.docx', '116_2018_ND-CP_m_397485.docx', '11_2001_L-CTN_m_71892.docx', '12_2022_TT-BCT_m_582930.docx', '144_2024_ND-CP_m_647300.docx', '14_2023_TT-BNNPTNT_m_594179.docx', '15_2022_TT-BNNPTNT_m_536367.docx', '15_2024_TT-BNNPTNT_m_635285.docx', '17_2022_TT-NHNN_m_548392.docx', '17_2026_TT-BNNMT_m_703611.docx', '18_2025_ND-CP_m_650598.docx', '199_2025_ND-CP_m_664759.docx', '19_2009_TT-BKHCN_m_96067.docx', '203_2025_QH15_m_661982.docx', '20_2009_TT-BXD_m_358651.docx', '20_2023_QH15_m_577937.docx', '20_2023_TT-BCT_m_587433.docx', '21_2025_ND-CP_m_647927.docx', '246_2016_TT-BTC_m_334309.docx', '259_2016_TT-BTC_m_334312.docx', '25_2022_TT-BTTTT_m_555757.docx', '25_2025_TT-BYT_m_669298.docx', '25_2026_TT-BYT_m_717485.docx', '29_2023_QD-TTg_m_593520.docx', '29_2026_ND-CP_m_696591.docx', '34_2023_TT-BTC_m_568907.docx', '356_2025_ND-CP_689146.docx', '35_2024_TT-BYT_m_645668.docx', '37_2011_QD-TTg_m_126596.docx', '42_2025_TT-BKHCN_m_686951.docx', '43_2024_QH15_m_618648.docx', '44_2018_TT-BTC_m_519044.docx', '46_2024_TT-BGTVT_m_645145.docx', '57_QD-TTg_m_102712.docx', '60_2023_ND-CP_m_577202.docx', '63_NQ-CP_m_425673.docx', '67_2021_TT-BTC_m_485532.docx', '67_2025_TT-BNNMT_m_683464.docx', '75_2025_TT-BNNMT_m_687673.docx', '809_QD-TTg_m_127920.docx', '85_2016_ND-CP_m_318857.docx', '87_2025_QH15_m_663144.docx', '87_2025_TT-BNNMT_m_695423.docx', '91_2025_QH15_m_665440.docx', '94_2025_TT-BNNMT_m_695179.docx']

#### **Handle unclassfied files**

In [75]:
# Temporary terms for classifying currently unclassified documents
# Every key must correspond to an existing ESG_TAXONOMY path
TEMP_ESG_KEYWORD_ALIASES = {
    # Environment
    ("Environment", "Air Emissions", "Non-GHG Air Emissions"): [
        "emission standard",
        "vehicle exhaust",
        "motorcycle emission",
        "motor vehicle emission",
        "vehicle emission",
        "exhaust emission"
    ],

    ("Environment", "Biodiversity", "Biodiversity"): [
        "plant quarantine",
        "animal quarantine",
        "plant protection",
        "quarantine pest",
        "invasive species",
        "aquatic resource",
        "fisheries resource"
    ],

    ("Environment",
     "Environmental management system, reporting and fines.",
     "Climate Risk Management"): [
        "natural disaster management",
        "disaster prevention",
        "disaster response",
        "emergency response"
    ],

    ("Environment",
     "Environmental management system, reporting and fines.",
     "Environmental Management System"): [
        "environmental remediation",
        "environmental improvement plan",
        "environmental impact assessment",
        "environmental permit",
        "environmental inspection"
    ],

    ("Environment",
     "Environmental management system, reporting and fines.",
     "Environmental Policy"): [
        "environmental technical regulation",
        "environmental protection regulation",
        "environmental protection requirement"
    ],

    ("Environment", "Sustainable Production", "Resource Efficiency"): [
        "mineral resource",
        "mineral reserve",
        "mineral extraction",
        "mineral operation",
        "natural resource exploitation"
    ],

    ("Environment", "Sustainable Production", "Energy"): [
        "electricity trade",
        "electricity supply",
        "power plant",
        "coal power",
        "electricity generation",
        "power generation"
    ],

    ("Environment", "Sustainable Production", "Waste"): [
        "sea dumping",
        "waste-related emergency",
        "waste incident",
        "waste response"
    ],

    ("Environment", "Sustainable Production", "Water"): [
        "marine pollution",
        "aquaculture environment",
        "sea water quality",
        "water discharge"
    ],

    # Social
    ("Social", "Human Rights", "Animal Welfare"): [
        "animal husbandry",
        "livestock breed",
        "animal breed",
        "livestock management"
    ],

    ("Social", "Product Safety", "Product Safety"): [
        "quality of goods",
        "conformity assessment",
        "medical supplies",
        "medical device",
        "product quality inspection",
        "technical conformity"
    ],

    ("Social", "Supply Chain", "Supply Chain"): [
        "origin traceability",
        "certificate of origin",
        "product origin",
        "supply origin"
    ],

    ("Social", "Community and Society", "Public Health"): [
        "plant quarantine",
        "animal quarantine",
        "disease prevention",
        "public health protection"
    ],

    # Governance
    ("Governance", "Taxes", "Taxes"): [
        "value-added tax",
        "export tariff",
        "import tariff",
        "special excise duty",
        "tax administration",
        "tax exemption"
    ],

    ("Governance", "Systemic Risk", "Systemic Risk"): [
        "financial risk",
        "insurance policy",
        "agricultural insurance",
        "risk management",
        "emergency management"
    ],

    ("Governance", "Business Ethics", "Business Ethics"): [
        "state inspection",
        "market inspection",
        "regulatory compliance",
        "administrative violation"
    ]
}

In [76]:
# Build all valid Domain → Group → Category paths
valid_taxonomy_paths = {
    (domain, group, category)
    for (domain, group), categories in ESG_TAXONOMY.items()
    for category in categories
}

# Find temporary paths that do not exist in ESG_TAXONOMY
invalid_alias_paths = (
    set(TEMP_ESG_KEYWORD_ALIASES)
    - valid_taxonomy_paths
)

print("Temporary alias paths:", len(TEMP_ESG_KEYWORD_ALIASES))
print("Invalid paths:", invalid_alias_paths)

Temporary alias paths: 16
Invalid paths: set()

In [77]:
# Classify text using official categories and temporary aliases
# temporary functions to work on unclassfied documents 
def classify_esg_temporary(body_text: str) -> tuple:

    normalized_text = body_text.lower()
    matches = []

    for (domain, group), categories in ESG_TAXONOMY.items():
        for category in categories:
            taxonomy_path = (domain, group, category)

            # Combine the official category name with temporary aliases
            keywords = [category.lower()]
            keywords += TEMP_ESG_KEYWORD_ALIASES.get(taxonomy_path, [])

            matched_keywords = [
                keyword
                for keyword in keywords
                if re.search(rf"\b{re.escape(keyword.lower())}\b",
                             normalized_text)]

            if matched_keywords:
                matches.append({
                    "domain": domain,
                    "group": group,
                    "category": category,
                    "matched_keywords": sorted(set(matched_keywords))})

    # Remove duplicate labels while preserving valid taxonomy results
    domains = sorted({match["domain"] for match in matches})
    groups = sorted({match["group"] for match in matches})
    categories = sorted({match["category"] for match in matches})

    return domains, groups, categories, matches

In [78]:
# Select successful documents with no ESG domain
unclassified_indexes = registry_df[
    (registry_df["status"] == "ok")
    & registry_df["esg_domains"].apply(
        lambda value: not isinstance(value, list) or len(value) == 0)
].index

temporary_results = []

for index in unclassified_indexes:
    cleaned_path = Path(registry_df.at[index, "cleaned_path"])
    cleaned_text = cleaned_path.read_text(encoding="utf-8")

    domains, groups, categories, matches = (
        classify_esg_temporary(cleaned_text)
    )

    # Update only documents that receive a temporary classification
    if domains:
        registry_df.at[index, "esg_domains"] = domains
        registry_df.at[index, "esg_category_groups"] = groups
        registry_df.at[index, "esg_categories"] = categories
        registry_df.at[index, "esg_matches"] = matches
        registry_df.at[index, "esg_review_status"] = (
            "pending_temporary_alias_review"
        )

    temporary_results.append({
        "source_filename": registry_df.at[index, "source_filename"],
        "esg_domains": domains,
        "esg_category_groups": groups,
        "esg_categories": categories,
        "matched_keywords": [
            keyword
            for match in matches
            for keyword in match["matched_keywords"]
        ]
    })

temporary_results_df = pd.DataFrame(temporary_results)

In [79]:
# Show newly classified documents first
display(temporary_results_df[temporary_results_df["esg_domains"].apply(bool)])

,source_filename,esg_domains,esg_category_groups,esg_categories,matched_keywords
0,02_2025_TT-BCT_m_648178.docx,"[Environment, Social]","[Product Safety, Sustainable Production]","[Energy, Product Safety]","[electricity generation, power generation, pow..."
3,04_2023_TT-BNNPTNT_m_576528.docx,"[Environment, Social]","[Biodiversity, Community and Society]","[Biodiversity, Public Health]","[plant protection, plant quarantine, plant qua..."
4,05_2015_TT-BNNPTNT_m_284118.docx,"[Environment, Social]","[Biodiversity, Community and Society]","[Biodiversity, Public Health]","[plant protection, plant quarantine, plant qua..."
6,07_2023_TT-BTC_m_556248.docx,"[Environment, Governance]","[Environmental management system, reporting an...","[Environmental Management System, Taxes]","[environmental remediation, tax administration]"
7,07_2026_TT-BNNMT_703640.docx,[Environment],[Biodiversity],[Biodiversity],[plant protection]
8,09_2009_TT-BKHCN_m_199506.docx,[Social],[Product Safety],[Product Safety],[conformity assessment]
9,1009_QD-BCT_m_656831.docx,[Environment],[Sustainable Production],[Energy],"[coal power, electricity generation]"
11,10_2021_TT-BKHDT_m_502913.docx,[Environment],"[Environmental management system, reporting an...",[Climate Risk Management],[disaster prevention]
12,112_2021_TT-BTC_m_529021.docx,"[Environment, Governance]","[Environmental management system, reporting an...","[Environmental Management System, Taxes]","[environmental remediation, tax administration]"
13,115_2014_TT-BTC_m_283734.docx,[Governance],[Systemic Risk],[Systemic Risk],[insurance policy]
14,116_2014_ND-CP_m_261978.docx,"[Environment, Social]","[Biodiversity, Community and Society]","[Biodiversity, Public Health]","[plant protection, plant quarantine, disease p..."
15,116_2018_ND-CP_m_397485.docx,[Environment],[Sustainable Production],[Energy],[power generation]
16,11_2001_L-CTN_m_71892.docx,[Environment],[Biodiversity],[Biodiversity],[plant protection]
18,144_2024_ND-CP_m_647300.docx,[Governance],[Taxes],[Taxes],"[export tariff, import tariff, tax administrat..."
19,14_2023_TT-BNNPTNT_m_594179.docx,[Social],[Human Rights],[Animal Welfare],[animal husbandry]
20,15_2022_TT-BNNPTNT_m_536367.docx,"[Environment, Social]","[Biodiversity, Community and Society, Product ...","[Biodiversity, Product Safety, Public Health]","[plant protection, disease prevention, conform..."
21,15_2024_TT-BNNPTNT_m_635285.docx,"[Environment, Social]","[Biodiversity, Community and Society, Human Ri...","[Animal Welfare, Biodiversity, Public Health]","[animal quarantine, animal quarantine, animal ..."
22,17_2022_TT-NHNN_m_548392.docx,"[Environment, Governance]","[Environmental management system, reporting an...","[Environmental Management System, Systemic Risk]","[environmental impact assessment, risk managem..."
24,18_2025_ND-CP_m_650598.docx,[Environment],[Sustainable Production],[Energy],"[electricity supply, electricity trade]"
25,199_2025_ND-CP_m_664759.docx,[Governance],[Taxes],[Taxes],[tax administration]
31,21_2025_ND-CP_m_647927.docx,[Governance],[Taxes],[Taxes],[tax administration]
32,246_2016_TT-BTC_m_334309.docx,[Governance],[Taxes],[Taxes],[tax administration]
33,259_2016_TT-BTC_m_334312.docx,[Governance],[Taxes],[Taxes],[tax administration]
37,29_2023_QD-TTg_m_593520.docx,[Social],[Product Safety],[Product Safety],[conformity assessment]
39,34_2023_TT-BTC_m_568907.docx,[Governance],[Taxes],[Taxes],[tax administration]
40,356_2025_ND-CP_689146.docx,"[Environment, Governance]","[Environmental management system, reporting an...","[Climate Risk Management, Systemic Risk, Taxes]","[emergency response, value-added tax, risk man..."
42,37_2011_QD-TTg_m_126596.docx,[Environment],[Sustainable Production],[Energy],"[electricity trade, power plant]"
45,44_2018_TT-BTC_m_519044.docx,"[Environment, Social]","[Biodiversity, Community and Society]","[Biodiversity, Public Health]","[animal quarantine, plant protection, animal q..."
46,46_2024_TT-BGTVT_m_645145.docx,[Social],[Product Safety],[Product Safety],[conformity assessment]
48,60_2023_ND-CP_m_577202.docx,"[Environment, Social]","[Air Emissions, Supply Chain]","[Non-GHG Air Emissions, Supply Chain]","[emission standard, certificate of origin]"
50,67_2021_TT-BTC_m_485532.docx,[Governance],"[Business Ethics, Taxes]","[Business Ethics, Taxes]","[state inspection, tax administration]"
51,67_2025_TT-BNNMT_m_683464.docx,[Social],[Product Safety],[Product Safety],[conformity assessment]
52,75_2025_TT-BNNMT_m_687673.docx,"[Environment, Social]","[Biodiversity, Community and Society]","[Biodiversity, Public Health]","[plant protection, plant quarantine, plant qua..."
53,809_QD-TTg_m_127920.docx,[Environment],[Biodiversity],[Biodiversity],[plant protection]
54,85_2016_ND-CP_m_318857.docx,"[Environment, Governance]","[Environmental management system, reporting an...","[Climate Risk Management, Systemic Risk]","[emergency response, risk management]"
57,91_2025_QH15_m_665440.docx,[Governance],[Business Ethics],[Business Ethics],[administrative violation]
58,94_2025_TT-BNNMT_m_695179.docx,[Social],"[Community and Society, Human Rights]","[Animal Welfare, Public Health]","[disease prevention, animal breed, animal husb..."

In [80]:
# Select documents that remain unclassified
still_unclassified = temporary_results_df[
    ~temporary_results_df["esg_domains"].apply(bool)].copy()

# Add document code and title from the main registry
still_unclassified = still_unclassified.merge(registry_df[["source_filename", "official_number", "title"]],
                                              on="source_filename", how="left")

# Rename columns for easier reading
still_unclassified = still_unclassified.rename(columns={
    "source_filename": "file_name",
    "official_number": "file_code"})

# Show the complete table without hiding rows or shortening titles
with pd.option_context("display.max_rows", None,
                       "display.max_colwidth", None):
    display(
        still_unclassified[[
            "file_code",
            "file_name",
            "title"
        ]].reset_index(drop=True)
    )

# Count all documents that remain unclassified
print("Total unclassified documents:", len(still_unclassified))

,file_code,file_name,title
0,03/2025/TT-BLDTBXH,03_2025_TT-BLDTBXH_m_646590.docx,ON WORK CLASSIFICATION STANDARDS BASED ON WORKING CONDITIONS
1,04/2021/TT-BCT,04_2021_TT-BCT_m_482504.docx,ON WORKING HOURS AND RESTING HOURS OF WORKERS WORKING IN UNDERGROUND MINES
2,06/2025/TT-BNNMT,06_2025_TT-BNNMT_m_671280.docx,ON NATIONAL TECHNICAL REGULATION ON EMISSIONS OF IN-USE AUTOMOBILES
3,10/2014/UBTVQH13,10_2014_UBTVQH13_m_267874.docx,ENVIRONMENTAL POLICE FORCES
4,12/2022/TT-BCT,12_2022_TT-BCT_m_582930.docx,"WORKING HOURS, REST PERIODS FOR WORKERS OPERATING, MAINTAINING, REPAIRING GAS DISTRIBUTION PIPELINES AND GAS WORKS"
5,17/2026/TT-BNNMT,17_2026_TT-BNNMT_m_703611.docx,"ON AMENDMENTS TO SOME ARTICLES OF CIRCULAR NO. 25/2018/TT-BNNPTNT DATED NOVEMBER 15, 2018 OF MINISTER OF AGRICULTURE AND ENVIRONMENT ON PROCEDURES FOR RISK ASSESSMENT OF AND LICENSE FOR IMPORT OF LIVE AQUATIC ANIMALS AND PLANTS AMENDED BY CIRCULAR NO. 01/2022/TT-BNNPTNT DATED JANUARY 18, 2022 ON AMENDMENTS TO CIRCULARS IN AQUACULTURE"
6,19/2009/TT-BKHCN,19_2009_TT-BKHCN_m_96067.docx,ON QUALITY CONTROL MEASURES FOR PRODUCTS AND GOODS SUBJECT TO INCREASED MANAGEMENT BEFORE MARKET CIRCULATION
7,203/2025/QH15,203_2025_QH15_m_661982.docx,AMENDMENTS TO CERTAIN ARTICLES OF THE CONSTITUTION OF THE SOCIALIST REPUBLIC OF VIETNAM
8,20/2009/TT-BXD,20_2009_TT-BXD_m_358651.docx,"ON AMENDMENTS TO THE CIRCULAR NO. 20/2005/TT-BXD DATED DECEMBER 20, 2005 BY THE MINISTRY OF CONSTRUCTION ON GUIDELINES FOR URBAN FORESTRY"
9,20/2023/QH15,20_2023_QH15_m_577937.docx,ELECTRONIC TRANSACTIONS
10,20/2023/TT-BCT,20_2023_TT-BCT_m_587433.docx,WORKING HOURS AND REST PERIODS OF OFFSHORE PETROLEUM WORKERS
11,25/2022/TT-BTTTT,25_2022_TT-BTTTT_m_555757.docx,"REGULATIONS ON DETERMINING IMPORTED MATERIALS, SUPPLIES AND COMPONENTS THAT ARE SUBJECT TO EXEMPTION FROM IMPORT TARIFFS AND DIRECTLY USED FOR PRODUCTION OF INFORMATION TECHNOLOGY PRODUCTS, DIGITAL PRODUCTS AND SOFTWARE PRODUCTS"
12,25/2025/TT-BYT,25_2025_TT-BYT_m_669298.docx,"ON ELABORATION OF THE LAW ON SOCIAL INSURANCE LAW, THE LAW ON OCCUPATIONAL SAFETY AND HYGIENE IN THE HEALTH SECTOR, AND CERTAIN ARTICLES OF THE LAW ON MEDICAL EXAMINATION AND TREATMENT"
13,25/2026/TT-BYT,25_2026_TT-BYT_m_717485.docx,ON AMENDMENTS TO SOME ARTICLES OF CIRCULAR NO. 01/2013/TT-BYT GUIDING THE MANAGEMENT OF MEDICAL TESTING QUALITY AT MEDICAL FACILITIES; CIRCULAR NO. 32/2023/TT-BYT ELABORATING SOME ARTICLES OF THE LAW ON MEDICAL EXAMINATION AND TREATMENT; CIRCULAR NO. 23/2024/TT-BYT ON ISSUANCE OF LIST OF TECHNIQUES IN MEDICAL EXAMINATION AND TREATMENT; AND CIRCULAR NO. 42/2025/TT-BYT ON HEALTH STANDARDS FOR RAILWAY VEHICLE OPERATORS
14,29/2026/ND-CP,29_2026_ND-CP_m_696591.docx,ON DOMESTIC CARBON EXCHANGE
15,35/2024/TT-BYT,35_2024_TT-BYT_m_645668.docx,ON THE BASIC QUALITY STANDARDS OF HOSPITALS
16,42/2025/TT-BKHCN,42_2025_TT-BKHCN_m_686951.docx,APPLICATION OF STANDARDS AND TECHNICAL REGULATIONS TO DATA CENTERS
17,43/2024/QH15,43_2024_QH15_m_618648.docx,"Amendments to certain Articles of Land Law No. 31/2024/QH15, Housing Law No. 27/2023/QH15, Law on Real Estate Business No. 29/2023/QH15 and Law on Credit Institutions No. 32/2024/QH15"
18,57/QD-TTg,57_QD-TTg_m_102712.docx,APPROVING THE PLACEMENT OF CULTURAL ATTACHES IN A NUMBER OF KEY FOREIGN COUNTRIES
19,63/NQ-CP,63_NQ-CP_m_425673.docx,"PROMULGATING LIST OF PLANNINGS FOR INVESTMENT IN AND DEVELOPMENT OF SPECIFIC GOODS, SERVICES AND PRODUCTS, AND DETERMINATION OF VOLUME OF PRODUCED, PROVIDED AND SOLD GOODS, SERVICES AND PRODUCTS TO BE ABROGATED AS REGULATED IN POINT D CLAUSE 1 ARTICLE 59 OF THE LAW ON PLANNING WITH THE APPROVAL OF THE PRIME MINISTER"
20,87/2025/QH15,87_2025_QH15_m_663144.docx,AMENDMENTS TO CERTAIN ARTICLES OF THE LAW ON PROMULGATION OF LEGISLATIVE DOCUMENTS
21,87/2025/TT-BNNMT,87_2025_TT-BNNMT_m_695423.docx,"ON PROCEDURES FOR SUBMITTING, RECEIVING, AND PROVIDING GEOLOGICAL AND MINERAL INFORMATION AND DATA"

Total unclassified documents: 22

KEEP: 
- 06/2025/TT-BNNMT: ON NATIONAL TECHNICAL REGULATION ON EMISSIONS OF IN-USE AUTOMOBILES
- 10/2014/UBTVQH13: ENVIRONMENTAL POLICE FORCES
- 29/2026/ND-CP: ON DOMESTIC CARBON EXCHANGE
- 42/2025/TT-BKHCN: APPLICATION OF STANDARDS AND TECHNICAL REGULATIONS TO DATA CENTERS

In [81]:
# Manually verified ESG labels for the four retained documents
MANUAL_ESG_OVERRIDES = {
    "06/2025/TT-BNNMT": {
        "esg_domains": ["Environment"],
        "esg_category_groups": ["Air Emissions"],
        "esg_categories": ["Non-GHG Air Emissions"]
    },

    "10/2014/UBTVQH13": {
        "esg_domains": ["Environment"],
        "esg_category_groups": [
            "Environmental management system, reporting and fines."
        ],
        "esg_categories": ["Environmental Policy"]
    },

    "29/2026/ND-CP": {
        "esg_domains": ["Environment"],
        "esg_category_groups": ["Air Emissions"],
        "esg_categories": ["GHG Policies"]
    },

    "42/2025/TT-BKHCN": {
        "esg_domains": ["Environment"],
        "esg_category_groups": ["Sustainable Production"],
        "esg_categories": ["Resource Efficiency"]
    }
}

In [82]:
# Apply manual ESG labels and retain all unclassified documents for later review
for document_code, labels in MANUAL_ESG_OVERRIDES.items():
    matching_indexes = registry_df.index[registry_df["official_number"].eq(document_code)]
    for index in matching_indexes:
        registry_df.at[index, "esg_domains"] = labels["esg_domains"]
        registry_df.at[index, "esg_category_groups"] = labels["esg_category_groups"]
        registry_df.at[index, "esg_categories"] = labels["esg_categories"]
        registry_df.at[index, "esg_matches"] = []
        registry_df.at[index, "esg_review_status"] = "manually_classified"

# Mark remaining unclassified documents without removing them
unclassified_mask = registry_df["esg_domains"].apply(lambda value: not isinstance(value, list) or len(value) == 0)
registry_df.loc[unclassified_mask, "esg_review_status"] = "needs_manual_review"

manual_documents = registry_df[registry_df["official_number"].isin(MANUAL_ESG_OVERRIDES)]
unclassified_documents = registry_df[unclassified_mask].copy()

display(manual_documents[["official_number", "title", "esg_domains", "esg_category_groups", "esg_categories", "esg_review_status"]])
display(unclassified_documents[["official_number", "title", "esg_review_status"]].reset_index(drop=True))

print("Manually classified:", len(manual_documents))
print("Needs manual review:", len(unclassified_documents))
print("Registry documents:", len(registry_df))

,official_number,title,esg_domains,esg_category_groups,esg_categories,esg_review_status
41,06/2025/TT-BNNMT,ON NATIONAL TECHNICAL REGULATION ON EMISSIONS ...,[Environment],[Air Emissions],[Non-GHG Air Emissions],manually_classified
76,10/2014/UBTVQH13,ENVIRONMENTAL POLICE FORCES,[Environment],"[Environmental management system, reporting an...",[Environmental Policy],manually_classified
233,29/2026/ND-CP,ON DOMESTIC CARBON EXCHANGE,[Environment],[Air Emissions],[GHG Policies],manually_classified
289,42/2025/TT-BKHCN,APPLICATION OF STANDARDS AND TECHNICAL REGULAT...,[Environment],[Sustainable Production],[Resource Efficiency],manually_classified

,official_number,title,esg_review_status
0,03/2025/TT-BLDTBXH,ON WORK CLASSIFICATION STANDARDS BASED ON WORK...,needs_manual_review
1,04/2021/TT-BCT,ON WORKING HOURS AND RESTING HOURS OF WORKERS ...,needs_manual_review
2,12/2022/TT-BCT,"WORKING HOURS, REST PERIODS FOR WORKERS OPERAT...",needs_manual_review
3,17/2026/TT-BNNMT,ON AMENDMENTS TO SOME ARTICLES OF CIRCULAR NO....,needs_manual_review
4,19/2009/TT-BKHCN,ON QUALITY CONTROL MEASURES FOR PRODUCTS AND G...,needs_manual_review
5,203/2025/QH15,AMENDMENTS TO CERTAIN ARTICLES OF THE CONSTITU...,needs_manual_review
6,20/2009/TT-BXD,ON AMENDMENTS TO THE CIRCULAR NO. 20/2005/TT-B...,needs_manual_review
7,20/2023/QH15,ELECTRONIC TRANSACTIONS,needs_manual_review
8,20/2023/TT-BCT,WORKING HOURS AND REST PERIODS OF OFFSHORE PET...,needs_manual_review
9,25/2022/TT-BTTTT,"REGULATIONS ON DETERMINING IMPORTED MATERIALS,...",needs_manual_review
10,25/2025/TT-BYT,ON ELABORATION OF THE LAW ON SOCIAL INSURANCE ...,needs_manual_review
11,25/2026/TT-BYT,ON AMENDMENTS TO SOME ARTICLES OF CIRCULAR NO....,needs_manual_review
12,35/2024/TT-BYT,ON THE BASIC QUALITY STANDARDS OF HOSPITALS,needs_manual_review
13,43/2024/QH15,Amendments to certain Articles of Land Law No....,needs_manual_review
14,57/QD-TTg,APPROVING THE PLACEMENT OF CULTURAL ATTACHES I...,needs_manual_review
15,63/NQ-CP,PROMULGATING LIST OF PLANNINGS FOR INVESTMENT ...,needs_manual_review
16,87/2025/QH15,AMENDMENTS TO CERTAIN ARTICLES OF THE LAW ON P...,needs_manual_review
17,87/2025/TT-BNNMT,"ON PROCEDURES FOR SUBMITTING, RECEIVING, AND P...",needs_manual_review

Manually classified: 4
Needs manual review: 18
Registry documents: 406

In [83]:
# check for duplicated files

In [84]:
# check for duplicated files & repeated official numbers 
official_number_counts = (
    registry_df.groupby("official_number")
    .size()
    .reset_index(name="document_count"))

duplicate_numbers = official_number_counts[
    official_number_counts["document_count"] > 1
].sort_values("document_count", ascending=False)

print("Repeated official numbers:", len(duplicate_numbers))
print("Documents involved:", duplicate_numbers["document_count"].sum())

display(duplicate_numbers)

Repeated official numbers: 3
Documents involved: 6

        official_number  document_count
112  13/2021/TT-BNNPTNT               2
192           21/QD-BCT               2
360        72/2020/QH14               2

In [85]:
# Show every file associated with a repeated official number
duplicate_files = registry_df[
    registry_df["official_number"].isin(
        duplicate_numbers["official_number"]
    )
][[
    "official_number",
    "doc_id",
    "source_filename",
    "title"
]].sort_values([
    "official_number",
    "source_filename"
])

display(duplicate_files)

,official_number,doc_id,source_filename,title
122,13/2021/TT-BNNPTNT,13_2021_TT-BNNPTNT_m_495964 (1),13_2021_TT-BNNPTNT_m_495964 (1).docx,PROVIDING FOR COMPLIANCE WITH REQUIREMENTS FOR...
123,13/2021/TT-BNNPTNT,13_2021_TT-BNNPTNT_m_495964,13_2021_TT-BNNPTNT_m_495964.docx,PROVIDING FOR COMPLIANCE WITH REQUIREMENTS FOR...
195,21/QD-BCT,21_QD-BCT_m_550028 (1),21_QD-BCT_m_550028 (1).docx,PROMULGATION OF THE TRANSITIONAL FRAMEWORK FOR...
196,21/QD-BCT,21_QD-BCT_m_550028,21_QD-BCT_m_550028.docx,PROMULGATION OF THE TRANSITIONAL FRAMEWORK FOR...
362,72/2020/QH14,72_2020_QH14_463512,72_2020_QH14_463512.docx,ON ENVIRONMENTAL PROTECTION
363,72/2020/QH14,72_2020_QH14_m_463512,72_2020_QH14_m_463512.docx,ON ENVIRONMENTAL PROTECTION

In [86]:
# Prefer original filenames over copies ending in "(1)"
registry_df = registry_df.sort_values("source_filename",
                                      key=lambda names: names.str.contains(r"\(\d+\)", regex=True))

# Keep one document for each official number
duplicate_mask = registry_df.duplicated("official_number", keep="first")
removed_duplicates = registry_df[duplicate_mask].copy()

registry_df = registry_df[~duplicate_mask].reset_index(drop=True)

display(removed_duplicates[["official_number", "source_filename", "title"]])

print("Duplicates removed:", len(removed_duplicates))
print("Documents remaining:", len(registry_df))

,official_number,source_filename,title
362,72/2020/QH14,72_2020_QH14_463512.docx,ON ENVIRONMENTAL PROTECTION
195,21/QD-BCT,21_QD-BCT_m_550028 (1).docx,PROMULGATION OF THE TRANSITIONAL FRAMEWORK FOR...
122,13/2021/TT-BNNPTNT,13_2021_TT-BNNPTNT_m_495964 (1).docx,PROVIDING FOR COMPLIANCE WITH REQUIREMENTS FOR...

Duplicates removed: 3
Documents remaining: 403

In [87]:
# Save the corrected complete registry
registry = registry_df.to_dict(orient="records")

registry_path = LOG_FOLDER / "corpus_registry.json"
registry_path.write_text(
    json.dumps(registry, indent=2, ensure_ascii=False),
    encoding="utf-8")

print("Saved documents:", len(registry))
print("Updated registry:", registry_path)

Saved documents: 403
Updated registry: /Users/tanggiee/Desktop/RAG_AI/esg_rag_project/outputs/logs/corpus_registry.json